;METADATA=(Diff=true, UseCommands=true)
[ServerSettings]
AdminPassword={AdminPassword}
NPCMindReadingMode=0
MaxNudity=0
ConfigVersion=13
BlueprintConfigVersion=25
BuildingPVPWhitelist=("80901","80111","80112","80915","80912")
PlayerKnockbackMultiplier=1
NPCKnockbackMultiplier=1
StructureDamageMultiplier=1
StructureHealthMultiplier=1
NPCRespawnMultiplier=1
NPCHealthMultiplier=1
PlayerDamageMultiplier=1
PlayerDamageTakenMultiplier=1
MinionDamageMultiplier=1
MinionDamageTakenMultiplier=1
NPCDamageMultiplier=1
NPCDamageTakenMultiplier=1
PlayerEncumbranceMultiplier=1
PlayerEncumbrancePenaltyMultiplier=1
PlayerMovementSpeedScale=1
PlayerStaminaCostSprintMultiplier=1
PlayerSprintSpeedScale=1
PlayerStaminaCostMultiplier=1
PlayerHealthRegenSpeedScale=1
PlayerXPRateMultiplier=1
PlayerXPKillMultiplier=1
PlayerXPHarvestMultiplier=1
PlayerXPCraftMultiplier=1
PlayerXPTimeMultiplier=1
DogsOfTheDesertSpawnWithDogs=False
CrossDesertOnce=True
ThrallExclusionRadius=100
MaxAggroRange=9000
FriendlyFireDamageMultiplier=0.25
CampsIgnoreLandclaim=True
AvatarDomeDurationMultiplier=1
AvatarDomeDamageMultiplier=1
NPCMaxSpawnCapMultiplier=1
PvPMountEnduranceDamageMultiplier=1
serverRegion=0
AmbientLifeEnabled=True
CraftFromStorageRadius=4000
BuildFromStorageRadius=4000
PVPBuildFromStorageRadius=600
PersonalCraftFromStorageRadius=4000
BuildingReplicationDistance=0
PVPEnabled=False
RestrictPVPTime=False
RestrictPVPBuildingDamageTime=False
PVPTimeMondayStart=0
PVPTimeTuesdayStart=0
PVPTimeWednesdayStart=0
PVPTimeThursdayStart=0
PVPTimeFridayStart=0
PVPTimeSaturdayStart=0
PVPTimeSundayStart=0
PVPTimeMondayEnd=0
PVPTimeTuesdayEnd=0
PVPTimeWednesdayEnd=0
PVPTimeThursdayEnd=0
PVPTimeFridayEnd=0
PVPTimeSaturdayEnd=0
PVPTimeSundayEnd=0
PVPEnabledMonday=False
PVPEnabledTuesday=False
PVPEnabledWednesday=False
PVPEnabledThursday=False
PVPEnabledFriday=False
PVPEnabledSaturday=False
PVPEnabledSunday=False
PVPBuildingDamageTimeMondayStart=0
PVPBuildingDamageTimeTuesdayStart=0
PVPBuildingDamageTimeWednesdayStart=0
PVPBuildingDamageTimeThursdayStart=0
PVPBuildingDamageTimeFridayStart=0
PVPBuildingDamageTimeSaturdayStart=0
PVPBuildingDamageTimeSundayStart=0
PVPBuildingDamageTimeMondayEnd=0
PVPBuildingDamageTimeTuesdayEnd=0
PVPBuildingDamageTimeWednesdayEnd=0
PVPBuildingDamageTimeThursdayEnd=0
PVPBuildingDamageTimeFridayEnd=0
PVPBuildingDamageTimeSaturdayEnd=0
PVPBuildingDamageTimeSundayEnd=0
PVPBuildingDamageEnabledMonday=False
PVPBuildingDamageEnabledTuesday=False
PVPBuildingDamageEnabledWednesday=False
PVPBuildingDamageEnabledThursday=False
PVPBuildingDamageEnabledFriday=False
PVPBuildingDamageEnabledSaturday=False
PVPBuildingDamageEnabledSunday=False
DisableBuildingDuringTimeRestrictedPVP=False
CombatModeModifier=0
ContainersIgnoreOwnership=True
LandClaimRadiusMultiplier=1
DisableLandclaimNotifications=True
BuildingPreloadRadius=80
CanDamagePlayerOwnedStructures=False
DynamicBuildingDamage=False
DynamicBuildingDamagePeriod=1800
CreativeModeServer=0
ServerPassword={Password}
ServerMessageOfTheDay=
KickAFKPercentage=80
KickAFKTime=2700
OfflinePlayersUnconsciousBodiesHours=168
ShowOnlinePlayers=0
CorpsesPerPlayer=10
PlayerCorpseLifeTime=1800
NPCCorpseLifeTime=600
ItemRepairMinimumDurability=0.100000001
ItemRepairDurabilityLossByRepairkitTier=(0.200000,0.200000,0.150000,0.100000,0.050000,0.025000)
ItemRepairDurabilityLossPenaltyChance=1
ItemConvertionMultiplier=1
ThrallConversionMultiplier=1
FuelBurnTimeMultiplier=1
CraftingCostMultiplier=1
StaminaRegenerationTime=3.75
StaminaExhaustionTime=3.75
StaminaStaticRegenRateMultiplier=1
StaminaMovingRegenRateMultiplier=1
PlayerStaminaRegenSpeedScale=1
StaminaOnConsumeRegenPause=1.10000002
StaminaOnExhaustionRegenPause=2
ThrallScoutingTimeMinutes=10
ThrallMinDistanceAwayFromHome=5000
ThrallTeleportingCooldown=10
MinionPopulationBaseValue=50
MinionPopulationPerPlayer=5
MinionOverpopulationCleanup=60
MinionOverpopulationAllowed=10
EnableFollowerDbno=True
UseMinionPopulationLimit=False
EnableFollowerRescueOnLandClaimOnly=True
EnableFollowerRescueInBuildExclusionZone=False
FollowerRescueCooldown=3600
DamageCooldownBeforeRescue=600
ThrallCorruptionRemovalMultiplier=1
PlayerCorruptionGainMultiplier=1
PlayerCorruptionGainFromSorceryMultiplier=1
AnimalPenCraftingTimeMultiplier=1
FeedBoxRangeMultiplier=1
BuildingDamageMultiplier=1
PathFollowingSendsAngularVelocity=False
UnconsciousTimeSeconds=1800
ConciousnessDamageMultiplier=1
ThrallDamageToPlayersMultiplier=0.5
ThrallDamageToNPCsMultiplier=0.5
DisableBuildingAbandonment=True
MaxBuildingDecayTime=1296000
MaxDecayTimeToAutoDemolish=604800
ThrallDecayTime=1296000
DisableThrallDecay=True
BuildingDecayTimePerScore=5400
BuildingDecayTimeMultiplier=1
DecayCleanupTimeMultiplier=2
DecayBonusTimeRate=600
DecayShowBuildingScore=False
EnableTargetLock=True
EnableFatalities=True
CachedLandClaimRadiusMultiplier=1
CachedBuildingReplicationDistance=0
ValidatePhysNavWalkWithRaycast=True
LocalNavMeshVisualizationFrequency=-1
LocalLandClaimVisualizationFrequency=-1
LocalLandClaimVisualizationRadius=3000
LocalLandClaimVisualizationChannel=0
UseLocalQuadraticAngularVelocityPrediction=False
LQAVPUseTime=0.150000006
LQAVPFadeTime=0.100000001
LQAVPMethod=2
NetworkSimulatedSmoothRotationTimeWithLQAVP=0.100000001
EnableClanMarkers=True
ValidatePlayerStats=False
bUndermeshDetectionEnabled=True
AllowedTimeUndermesh=1
CapCharacterLayoutScalarParams=False
EventLogPvPCauserPrivacy=2
EventLogPvECauserPrivacy=1
serverVoiceChat=1
AvatarsDisabled=False
RestrictAvatarSummoningTime=False
AvatarSummoningTimeWeekdayStart=0
AvatarSummoningTimeWeekdayEnd=0
AvatarSummoningTimeWeekendStart=0
AvatarSummoningTimeWeekendEnd=0
AvatarLifetime=600
AvatarSummonTime=60
MaxDeathMapMarkers=3
IsBattlEyeEnabled=False
ServerTransferEnabled=True
ServerTransferServersWhitelist=
MaxAllowedPing=0
AllowFamilySharedAccount=True
RegionAllowAfrica=True
RegionAllowAsia=True
RegionAllowCentralEurope=True
RegionAllowEasternEurope=True
RegionAllowWesternEurope=True
RegionAllowNorthAmerica=True
RegionAllowOceania=True
RegionAllowSouthAmerica=True
RegionBlockList=
ServerModList=
BuildingPickupEnabled=True
PoiProtectionEnabled=False
EventSystemEnabled=True
StabilityLossMultiplier=1
BuildingValidationEnabled=False
AllowBuildingAnywhere=False
HealthbarVisibilityDistance=15000
ServerMergeOutgoingTime=0
ServerMergeDestination=
ServerRetirementTime=0
DisableChatFormatting=True
EnableLoginQueue=True
DisconnectionGraceTime=180
bCanBeDamaged=True
