[Host Settings]
ServerName="{ServerName}"
Password="{Password}"
;Server name. Avoid using the word "Official" in your server name or your server may not start or showup in the server list.
SaveName="DedicatedSaveMP"
;Use this to place your server in a specific bucket and use it when searching. Changing this will make your server not show up in the default server list, users will have to indicate the specific SearchID
SearchID="HumanitZ_Dedicated"
;Used for admin access, you can use /adminaccess <password> in game to access admin commands.
AdminPass="{AdminPassword}"
MaxPlayers={MaxPlayers}
;Used to reserve slots for certain players. Add their NetID to F_ReservedSlots.txt file. Set to 0 to disable reserving slots.
ReserveSlots=0
;Use it to execute remote command, use any rcon compatible program. Enabling this will allow server ping being displayed in server browser
RCONEnabled={EnableRcon}
;TCP port for rcon
RConPort={RCONPort}
RCONPass="{RCONPassword}"
;If set to true notification about dead players will be disabled. Admins will still be able to see them.
NoDeathFeedback=true
;If set to true notification about players joining and leaving the server will be disabled. Admins will still be able to see them.
NoJoinFeedback=true
;When set to true players will only have access to random coast spawns and spawn point if available
LimitedSpawns=false
;When true your server will reject known banned players from official servers
UseGlobalBanList=true
;When disabled (false), players will not be able to join the server when using family share feature.
AllowFamilySharing=true

[World Settings]
;Build ID, only relevant inside REF_GameServerSettings.ini because that gets updated when pulling server files off steam CMD.
Version=39
;Multiplier for player experience gain. 1 is default, 2 would be twice as much experience, 0.5 would be half as much experience.
XpMultiplier=1
;The interval in seconds at which the server saves the world. Set to 0 to disable auto-saving.
SaveIntervalSec=300
;When set to true the player that died will lose their character and have to create a a new one
PermaDeath=false
;0=Lose nothing, 1=Lose backpack and weapon in hand, 2=Previous + pockets and backpack, 3=All previous + Equipment
OnDeath=2
;Time in second to be able to spawn again after death
RespawnTimer=15
;false/true=Off/On. This will also affect the ability to interact with player items such as cars and containers
PVP={IsPvp}
;Time in seconds before player is allowed to log out if PVP is enabled. Set to 0 to disable logout timer.
LogoutTimer=30
; Set whether air drops are enabled or not
AirDrop=true
;How many game days between each AirDrop
AirDropInterval=1
;If true when weapon durability reaches 0%, the weapon will break and be removed from the player's inventory. Set to false to disable weapon breaking.
WeaponBreak=true
;How many cars you are allowed to own. Non owned cars can't be driven but can be looted. When a car is claimed you can Lock/unlock it and use it as normal
MaxOwnedCars=2
;When true time passes if eveyone performs the sleep emote at the same time, false=Passing time is disabled
MultiplayerSleep=false
;Loot does respawn, false=Never respawn
LootRespawn=true
;If loot respawn is enabled, this is the time in minutes it takes for loot containers to respawn.
LootRespawnTimer=60
;If loot respawn is enabled, this is the time in minutes it takes for pickup items to respawn.
PickupRespawnTimer=90
;From 0 to 4 (Scarce, low, default, Plentiful, abundant) Same for all rarities below.
RarityFood=2
RarityDrink=2
RarityMelee=2
RarityRanged=2
RarityAmmo=2
RarityArmor=2
RarityResources=2
RarityOther=2
;Health difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
ZombieDiffHealth=1
;Speed difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
ZombieDiffSpeed=2
;Damage difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
ZombieDiffDamage=3
;Zombie amount multiplier 2 for example would mean twice as many zombies. 0.5 would mean half as many zombies.
ZombieAmountMulti=1
;Human bandit amount multiplier 2 for example would mean twice as many human bandits. 0.5 would mean half as many human bandits.
HumanAmountMulti=1
;Zombie dog mainly appear at night. 2 for example would mean twice as many zombie dogs. 0.5 would mean half as many zombie dogs.
ZombieDogMulti=1
;The time in minutes it takes for zombies to respawn, set to 0 to disable zombie respawning.
ZombieRespawnTimer=90
;The time in minutes it takes for human bandits to respawn, set to 0 to disable human bandit respawning.
HumanRespawnTimer=90
;Human bandit difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
HumanHealth=2
;Human bandit speed difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
HumanSpeed=2
;Human bandit damage difficulty where 0=Very Easy, 1=Easy, 2=Default, 3=Hard, 4=Very Hard, 5=Nightmare
HumanDamage=2
;Animal spawn multiplier, default 1
AnimalMulti=1
;The time in minutes it takes for animals to respawn, set to 0 to disable animal respawning.
AnimalRespawnTimer=90
;0=Summer, 1=Autum, 2=Winter, 3=Spring
StartingSeason=1
;How many game days each season lasts
DaysPerSeason=5
;Day duration in minutes
DayDur=40
;Night duration in minutes
NightDur=20
;How fast your vitals drain 0=Slow, 1=Normal, 2=Fast
VitalDrain=1
;Enable finding dog companions you can recruit set to true to enable or false to disable
DogEnabled=true
;Allow players to recruit companion dogs by dropping food and claiming the dog. Set to false to disable.
RecruitDog=true
;The maximum amount of companion dogs you can find in the world. Dogs will respawn when needed.
DogNum=8
;Health multiplier of player placed buildings. By default set to 1.
BuildingHealth=1
;Dog companion health 0=Low 1=Default 2=High This is not a multiplier, it is a set value for dog companion health.
CompanionHealth=1
;Dog companion damage 0=Low 1=Default 2=High This is not a multiplier, it is a set value for dog companion damage.
CompanionDmg=1
;Enable players to dismantle their own buildings.
AllowDismantle=true
;Enable Players are able to dismantle house props.
AllowHouseDismantle=true
;If true You WILL NOT be allowed to build in someone's spawn point area. For clans only non recruit members can.
Territory=true
;Experimental: When false, certain buildables require a foundation. This reduces floating buildings. Use at your own risk. Provide feedback to devs if you encounter any issues.
FreeBuild=true
;When true, players are not allowed to build in certain zones.
NoBuildZone=true
;How many real days it takes for a spawn point to go from 100% health to being destroyed. Once spawn point is gone, player built stuff will also start decaying
Decay=7
;How many real days it takes for player built buildings to fully decay. No decay happens If a spawn point is protecting it. 0 to disable.
BuildingDecay=7
;How long in game days it takes for dropped pickups to be destroyed (Pickups part of the world and placed items will not be considered), a value of 0 means no cleanup is done.
PickupCleanup=6
;How long in minutes it takes for the white blueprint building to be destroyed, a value of 0 means no cleanup is done.
FakeBuildingCleanup=3000
;Contols how fast food decays 0=Disabled 1=Default. It's a multiplier so if you need to slow down decay by half the value would be 0.5. Values greater than 1 will speed it up.
FoodDecay=1
;Controls how fast house generator consumes fuel. 0.01 to 4. It's a multiplier where 1 is default and less than 1 will slows it down.
GenFuel=1
;After how many real days a claimed car will be recycled into the pool and randomly spawned somewhere. Set to 0 to disable car recycling.
RecycleCar=14
;Sleep deprivation effect false=Disabled true=Enabled
Sleep=true
;When enabled and server is empty time doesn't pass.
FreezeTime=true
;Map is divided into 3 segments, objects that need to spawmn reasonabiliy far are put in Seg0 like houses. Broken cars and other similar objects are put in Seg1. Leave it as is unless you want to tweak performance and spawn distance
;Look at the map as a grid. Seg0=12 means map is divided into 12x12 grid. Once inside a grid, objects inside that grid will spawn.
MapSeg0=12
MapSeg1=20
MapSeg2=60
;When set to 1 or true voice chat will be enabled, set 0 or false to disable
Voip=true
;The game will sometimes spawn AI event such as zombies or human raiding your location. How frequence the event is where 0 = Disabled, 1 Low, 2 = Default, 3 = High, 4 = Insane
AIEvent=2
;Below you can tweak the odds of each weather type. The current season will still dictate which weather types can spawn.
Weather_ClearSky=1
Weather_Cloudy=1
Weather_Foggy=1
Weather_LightRain=1
Weather_Rain=1
Weather_Thunderstorm=1
Weather_LightSnow=1
Weather_Snow=1
Weather_Blizzard=1
