// ============================================================================
// PROJECT: Synix Game Server Control Panel
// AUTHOR: Jason Turner (ubidzz)
// COPYRIGHT: © 2026 All Rights Reserved.
// 
// LEGAL NOTICE:
// This source code is proprietary and confidential. 
// 1. Permission is granted for PERSONAL, NON-COMMERCIAL use only.
// 2. You may modify this code for your own use, but you may NOT redistribute,
//    rebrand, or sell this code or derivative works without written consent.
// 3. The "Synix" brand and logic remain the property of Jason Turner.
// ============================================================================
using Synix_Control_Panel.SynixApp.ServerHandler;

namespace Synix_Control_Panel.SynixApp.Database
{
	public static class GameDatabase
	{
		public static IReadOnlyList<GameInfo> GetGames => games;

		private static readonly IReadOnlyList<GameInfo> games =
		[
			new() {
				Game = "Subsistence",
				AppID = "1362640",
				ExeName = @"Binaries\Win64\UDK.exe",
				RequiredArgs = "server {map}?steamsockets -log -port={port} -queryport={query} -MaxPlayers={MaxPlayers} -pass=\"{pass}\" -adminpass=\"{adminpass}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"UDKGame\Config\UDKDedServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["coldmap1"],
				GameModes = ["easy", "normal", "hardcore"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "HumanitZ",
				AppID = "2728330",
				ExeName = "TSSGameServer.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -steamservername=\"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"HumanitZServer\GameServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Soulmask",
				AppID = "3017310",
				ExeName = @"WS\Binaries\Win64\WSServer-Win64-Shipping.exe",
				RequiredArgs = "{map} -server -log -UTF8Output -Port={port} -QueryPort={query} -EchoPort=18888 -mainserverport=19000 -SteamServerName=\"{ServerName}\" -MaxPlayers={MaxPlayers} -PSW=\"{pass}\" -adminpsw=\"{adminpass}\" -{mode} -serverid=1 -forcepassthrough -SteamAppId={steamAppID} -online=Steam",
				RelativeConfigPath = @"WS\Saved\GameplaySettings\GameXishu.json",
				Port = 8777,
				QueryPort = 27016,
				Maps = ["Level01_Main", "DLC_Level01_Main"],
				GameModes = ["PVP", "PVE"],
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "7 Days to Die",
				AppID = "294420",
				ExeName = "7DaysToDieServer.exe",
				RequiredArgs = "-quit -batchmode -nographics -configfile=\"serverconfig.xml\" -ServerPort={port} -ServerName=\"{ServerName}\" -GameName=\"{Identity}\" -ServerPassword=\"{pass}\" -ServerMaxPlayerCount={MaxPlayers} -GameWorld=\"{map}\" -WorldGenSeed=\"{seed}\" -WorldGenSize={world_size} -SteamAppId={steamAppID} -dedicated",
				Port = 26900,
				QueryPort = 26900,
				WorldSeed = "12345",
				WorldSize = 6144,
				RelativeConfigPath = "serverconfig.xml",
				Format = ConfigFormat.XML,
				Maps = ["Navezgane", "Pregen6k", "Pregen8k", "Pregen10k", "RWG"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Valheim",
				AppID = "896660",
				ExeName = "valheim_server.exe",
				RequiredArgs = "-nographics -SteamAppId={steamAppID} -batchmode -name \"{ServerName}\" -port {port} -world \"{map}\" -password \"{pass}\"",
				Port = 2456,
				QueryPort = 2457,
				Format = ConfigFormat.StandardINI,
				Maps = ["Dedicated"]
			},
			new() {
				Game = "Palworld",
				AppID = "2394010",
				ExeName = "Pal\\Binaries\\Win64\\PalServer-Win64-Shipping.exe",
				RequiredArgs = "EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS -SteamAppId={steamAppID} -port={port} -queryport={query} -players={MaxPlayers} -ServerName=\"{ServerName}\"",
				RelativeConfigPath = "Pal\\Saved\\Config\\WindowsServer\\PalWorldSettings.ini",
				Port = 8211,
				QueryPort = 27015,
				Maps = ["DefaultWorld"],
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "ARK: Survival Evolved",
				AppID = "376030",
				ExeName = @"ShooterGame\Binaries\Win64\ShooterGameServer.exe",
				RequiredArgs = "{map}?SessionName=\"{ServerName}\"?ServerPassword=\"{pass}\"?Port={port}?QueryPort={query}?MaxPlayers={MaxPlayers}?ServerAdminPassword=\"{adminpass}\" -server -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"ShooterGame\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["TheIsland", "ScorchedEarth_P", "Aberration_P", "Extinction", "Genesis", "Ragnarok", "TheCenter", "Valguero_P", "CrystalIsles", "Gen2", "LostIsland", "Fjordur"],
				GameModes = ["PVE", "PVP"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "ARK: Survival Ascended",
				AppID = "2430930",
				ExeName = @"ShooterGame\Binaries\Win64\ArkServer.exe",
				RequiredArgs = "{map}?SessionName=\"{ServerName}\"?ServerPassword=\"{pass}\"?QueryPort={query}?MaxPlayers={MaxPlayers}?ServerAdminPassword=\"{adminpass}\" -port={port} -server -log -SteamAppId={steamAppID} {rcon}",
				RconSyntax = "?RCONEnabled=True?RCONPort={rcon_port}",
				RelativeConfigPath = @"ShooterGame\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7777,
				QueryPort = 27015,
				Maps = [ "TheIsland_WP", "ScorchedEarth_WP", "TheCenter_WP", "Aberration_WP", "Extinction_WP", "Valguero_WP", "Ragnarok_WP", "LostColony_WP", "Astraeos_WP", "Genesis_WP"],
				GameModes = ["PVE", "PVP"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Sons Of The Forest",
				AppID = "2465200",
				ExeName = "SonsOfTheForestDS.exe",
				RequiredArgs = "-userdatapath \"Saves\" -port {port} -queryport {query} -maxplayers {MaxPlayers} -servername \"{ServerName}\" -password \"{pass}\" -SteamAppId={steamAppID}",
				Port = 8766,
				QueryPort = 27016,
				RelativeConfigPath = @"userdata\dedicated_server.cfg",
				Format = ConfigFormat.JSON,
				Maps = ["Default"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Enshrouded",
				AppID = "2278520",
				ExeName = "enshrouded_server.exe",
				RelativeConfigPath = "enshrouded_server.json",
				RequiredArgs = "-port {port} -queryport {query} -SteamAppId={steamAppID}",
				Format = ConfigFormat.JSON,
				Port = 15636,
				QueryPort = 15637,
				Maps = ["Embervale"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Core Keeper",
				AppID = "1963720",
				ExeName = "CoreKeeperServer.exe",
				RequiredArgs = "-world {map} -worldname \"{ServerName}\" -port {port} -maxplayers {MaxPlayers} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = @"DedicatedServer\ServerConfig.json",
				Format = ConfigFormat.JSON,
				Maps = ["0", "1", "2"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Terraria",
				AppID = "105610", 
				ExeName = "TerrariaServer.exe",
				RequiredArgs = "-port {port} -maxplayers {MaxPlayers} -world \"{map}\" -password \"{pass}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 7777,
				RelativeConfigPath = "serverconfig.txt",
				Format = ConfigFormat.StandardINI,
				Maps = ["World1.wld"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Team Fortress 2",
				AppID = "232250",
				ExeName = "srcds.exe",
				RequiredArgs = "-game tf -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +sv_password \"{pass}\" +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"tf\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ctf_2fort", "pl_upward", "cp_dustbowl", "koth_harvest"]
			},
			new() {
				Game = "Left 4 Dead 2",
				AppID = "222860",
				ExeName = "srcds.exe",
				RequiredArgs = "-game left4dead2 -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +mp_gamemode {mode} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"left4dead2\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["c1m1_hotel", "c2m1_highway", "c8m1_apartment", "c14m1_junkyard", "c1m4_atrium"],
				GameModes = ["coop", "versus", "survival", "scavenge"]
			},
			new() {
				Game = "Squad",
				AppID = "403240",
				ExeName = "SquadGameServer.exe",
				RequiredArgs = "Port={port} QueryPort={query} FIXEDMAXPLAYERS={MaxPlayers} +map {map} -SteamAppId={steamAppID}",
				Port = 7787,
				QueryPort = 27165,
				RelativeConfigPath = @"SquadGame\ServerConfig\Server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Mutaha_AAS_v1", "Gorodok_RAAS_v1", "Fallujah_AAS_v1"]
			},
			new() {
				Game = "Stationeers",
				AppID = "600760",
				ExeName = "rocketstation_DedicatedServer.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -autostart -loadlatest {map} -settings StartLocalHost true ServerVisible true ServerMaxPlayers {MaxPlayers} ServerPort {port} ServerName \"{ServerName}\" ServerPassword \"{pass}\"",
				Port = 27016,
				QueryPort = 27015,
				RelativeConfigPath = "default.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Moon", "Mars", "Europa", "Mimas"]
			},
			new() {
				Game = "Empyrion - Galactic Survival",
				AppID = "530870",
				ExeName = "EmpyrionDedicated.cmd",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -port {port} -queryport {query} -logFile Logs\\current.log",
				Port = 30000,
				QueryPort = 30001,
				Format = ConfigFormat.StandardINI,
				Maps = ["Default Multiplayer"]
			},
			new() {
				Game = "Stormworks: Build and Rescue",
				AppID = "1247090",
				ExeName = "server64.exe",
				RequiredArgs = "+server_name \"{ServerName}\" +port {port} +password \"{pass}\" +max_players {MaxPlayers} -SteamAppId={steamAppID}",
				Port = 25564,
				QueryPort = 25564,
				RelativeConfigPath = "server_config.xml",
				Format = ConfigFormat.XML,
				Maps = ["Default"]
			},
			new() {
				Game = "The Forest",
				AppID = "556450",
				ExeName = "TheForestDedicatedServer.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -savefolderpath \"Saves\" -serverip 0.0.0.0 -serverplayers {MaxPlayers} -serverpassword \"{pass}\" -serverpassword_admin \"{adminpass}\" -serverport {port} -serverqueryport {query}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = @"ds\Server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Saves"]
			},
			new() {
				Game = "Barotrauma",
				AppID = "1026340",
				ExeName = "DedicatedServer.exe",
				RequiredArgs = "-port {port} -queryport {query} -name \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "serversettings.xml",
				Format = ConfigFormat.XML,
				Maps = ["Campaign"]
			},
			new() {
				Game = "Abiotic Factor",
				AppID = "2857200",
				ExeName = @"AbioticFactor\Binaries\Win64\AbioticFactorServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Listen -log -MaxPlayers={MaxPlayers} -Port={port} -QueryPort={query} -ServerPassword=\"{pass}\" -SteamAppId={steamAppID}",
				RelativeConfigPath = @"AbioticFactor\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7777,
				QueryPort = 27015,
				Maps = ["Cascade"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Icarus",
				AppID = "2089300",
				ExeName = @"Icarus\Binaries\Win64\IcarusServer-Win64-Shipping.exe",
				RequiredArgs = "{map} -Log -SteamServerName=\"{ServerName}\" -Port={port} -QueryPort={query} -SteamAppId={steamAppID}",
				RelativeConfigPath = @"Icarus\Saved\Config\WindowsServer\ServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 17777,
				QueryPort = 27016,
				Maps = ["Olympus", "Styx", "Prometheus", "Elysium"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Don't Starve Together",
				AppID = "343050",
				ExeName = @"bin\dontstarve_dedicated_server_nullrenderer.exe",
				RequiredArgs = "-console -cluster \"{Identity}\" -shard {map} -SteamAppId={steamAppID}",
				Port = 10999,
				QueryPort = 27016,
				RelativeConfigPath = @"DoNotStarveTogether\{Identity}\cluster.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Master", "Caves"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Killing Floor 2",
				AppID = "232130",
				ExeName = @"Binaries\Win64\KFServer.exe",
				RequiredArgs = "{map}?Game=KFGameContent.KFGameInfo_{mode}?AdminPassword=\"{adminpass}\"?GamePassword=\"{pass}\" -Port={port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"KFGame\Config\PCServer-KFGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["KF-BioticsLab", "KF-BurningParis", "KF-Outpost", "KF-ZedLanding"],
				GameModes = ["Survival", "Versus"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "The Front",
				AppID = "2612550", 
				ExeName = @"ProjectWar\Binaries\Win64\TheFrontServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Listen?MaxPlayers={MaxPlayers}?ServerName=\"{ServerName}\"?ServerPassword=\"{pass}\"?ServerAdminPassword=\"{adminpass}\"?Port={port}?QueryPort={query} -server -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"ProjectWar\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["TheFront"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Smalland: Survive the Wilds",
				AppID = "808040", 
				ExeName = "start-server.bat",
				RequiredArgs = "{map}?Listen -log -ServerName=\"{ServerName}\" -Password=\"{pass}\" -MaxPlayers={MaxPlayers} -Port={port} -SteamAppId={steamAppID}",
				RelativeConfigPath = @"SMALLAND\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7777,
				QueryPort = 27015,
				Maps = ["Smalland"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Sunkenland",
				AppID = "2667530",
				ExeName = "Sunkenland-DedicatedServer.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -serverName \"{ServerName}\" -password \"{pass}\" -port {port} -maxPlayers {MaxPlayers}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"Worlds\{Identity}\ServerConfig.txt",
				Format = ConfigFormat.StandardINI,
				Maps = ["World1"]
			},
			new() {
				Game = "Risk of Rain 2",
				AppID = "1180760",
				ExeName = "Risk of Rain 2.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -server_port {port} -server_query_port {query}",
				Port = 27015,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				Maps = ["Default"]
			},
			new() {
				Game = "V Rising",
				AppID = "1829350",
				ExeName = "VRisingServer.exe",
				RequiredArgs = "-persistentDataPath .\\save-data -server -ServerName \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 9876,
				QueryPort = 9877,
				RelativeConfigPath = @"VRisingServer_Data\StreamingAssets\Settings\ServerHostSettings.json",
				Format = ConfigFormat.JSON,
				Maps = ["World1"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "DayZ",
				AppID = "223350",
				ExeName = "DayZServer_x64.exe",
				RequiredArgs = "-config=serverDZ.cfg -port={port} -name=\"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 2302,
				QueryPort = 27016,
				RelativeConfigPath = "serverDZ.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ChernarusPlus"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Conan Exiles",
				AppID = "443030",
				ExeName = @"ConanSandbox\Binaries\Win64\ConanSandboxServer.exe",
				RequiredArgs = "{map}?Listen?MaxPlayers={MaxPlayers}?ServerName=\"{ServerName}\"?ServerPassword=\"{pass}\"?Port={port}?QueryPort={query} -server -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Maps = ["TheExiledLands"],
				RelativeConfigPath = @"ConanSandbox\Saved\Config\WindowsServer\ServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				GameModes = ["PVE", "PVP"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Garry's Mod",
				AppID = "4020",
				ExeName = "srcds.exe",
				RequiredArgs = "-game garrysmod -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +gamemode {mode} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"garrysmod\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["gm_construct", "gm_flatgrass", "ttt_67thway_v3", "ttt_clue", "rp_downtown_v4c_v2", "zs_obj_vertigo", "ph_office", "mu_clue", "dr_playstation"],
				GameModes = ["sandbox", "ttt", "darkrp", "zombiesurvival", "prophunt", "murder", "deathrun", "basewars"]
			},
			new() {
				Game = "Project Zomboid",
				AppID = "380870",
				ExeName = "StartServer64.bat",
				RequiredArgs = "-port {port} -server -servername \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 16261,
				QueryPort = 16262,
				RelativeConfigPath = @"Zomboid\Server\{Identity}.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Muldraugh, KY"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Mordhau",
				AppID = "629800",
				ExeName = @"Mordhau\Binaries\Win64\MordhauServer-Win64-Shipping.exe",
				RequiredArgs = "{map} -log -port={port} -QueryPort={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Mordhau\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["FFA_Contraband", "SKM_Camp"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Valheim (Crossplay)",
				AppID = "896660",
				ExeName = "valheim_server.exe",
				RequiredArgs = "-nographics -batchmode -name \"{ServerName}\" -port {port} -world \"{map}\" -password \"{pass}\" -crossplay -SteamAppId={steamAppID}",
				Port = 2456,
				QueryPort = 2457,
				Format = ConfigFormat.StandardINI,
				Maps = ["Dedicated"]
			},
			new()
			{
				Game = "Satisfactory",
				AppID = "1690800",
				ExeName = @"FactoryGame\Binaries\Win64\FactoryServer-Win64-Shipping.exe",
				RequiredArgs = "-log -unattended -ServerQueryPort={query} -multihome=0.0.0.0 -port={port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 15777,
				RelativeConfigPath = @"FactoryGame\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Satisfactory"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Unturned",
				AppID = "1110390",
				ExeName = "Unturned.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} \"+InternetServer/{Identity}\" +map {map} -port {port} -password \"{pass}\" {mode}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = @"Servers\{Identity}\Server\Commands.dat",
				Format = ConfigFormat.StandardINI,
				Maps = ["PEI", "Washington", "Russia", "Germany", "Hawaii"],
				GameModes = ["PVP", "PVE"]
			},
			new()
			{
				Game = "Space Engineers",
				AppID = "298740",
				ExeName = @"DedicatedServer64\SpaceEngineersDedicated.exe",
				RequiredArgs = "-noconsole -ignorelastsession -port {port} -SteamAppId={steamAppID}",
				Port = 27016,
				QueryPort = 27016,
				GameModes = ["Creative"],
				RelativeConfigPath = @"Instance\SpaceEngineers-Dedicated.cfg",
				Format = ConfigFormat.XML,
				Maps = ["StarSystem", "AlienPlanet", "EmptyWorld"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Arma 3",
				AppID = "233780",
				ExeName = "arma3server.exe",
				RequiredArgs = "-port={port} -name=\"{ServerName}\" -config=server.cfg -world={map} -SteamAppId={steamAppID}",
				Port = 2302,
				QueryPort = 2303,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["empty", "Altis", "Stratis", "Tanoa", "Malden"]
			},
			new()
			{
				Game = "Insurgency: Sandstorm",
				AppID = "581330",
				ExeName = @"Insurgency\Binaries\Win64\InsurgencyServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Scenario={map}?MaxPlayers={MaxPlayers} -port={port} -queryport={query} -hostname=\"{ServerName}\" -password=\"{pass}\" -SteamAppId={steamAppID}",
				Port = 27102,
				QueryPort = 27131,
				RelativeConfigPath = @"Insurgency\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Refinery", "Farmhouse", "Hideout", "Crossing"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Mount & Blade II: Bannerlord",
				AppID = "1863440",
				ExeName = @"bin\Win64_Shipping_Server\Bannerlord.DedicatedServer.exe",
				RequiredArgs = "_MODULES_*Native*Multiplayer*_MODULES_ /dedicatedcustomserverconfigfile {map} /port {port} -SteamAppId={steamAppID}",
				Port = 7230,
				QueryPort = 7230,
				Maps = ["CustomServerconfig.txt"],
				Format = ConfigFormat.StandardINI,
			},
			new()
			{
				Game = "Arma Reforger",
				AppID = "1874900",
				ExeName = "ArmaReforgerServer.exe",
				RequiredArgs = "-config \"{map}\" -profile \"profile\" -maxPlayers {MaxPlayers} -port {port} -SteamAppId={steamAppID}",
				Port = 2001,
				QueryPort = 2001,
				RelativeConfigPath = @"configs\server.json",
				Format = ConfigFormat.JSON,
				Maps = ["server.json"]
			},
			new()
			{
				Game = "Avorion",
				AppID = "565060",
				ExeName = @"bin\AvorionServer.exe",
				RequiredArgs = "--galaxy-name \"{map}\" --seed {seed} --server-name \"{ServerName}\" --admin \"{adminpass}\" --port {port} --use-steam-networking 1 -SteamAppId={steamAppID}",
				Port = 27000,
				QueryPort = 27003,
				RelativeConfigPath = @"galaxies\avorion_galaxy\server.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["galaxy"]
			},
			new()
			{
				Game = "PixARK",
				AppID = "824360",
				ExeName = @"ShooterGame\Binaries\Win64\PixARKServer.exe",
				RequiredArgs = "{map}?Listen?SessionName=\"{ServerName}\"?ServerPVE={mode}?ServerPassword=\"{pass}\"?ServerAdminPassword=\"{adminpass}\"?Port={port}?QueryPort={query} {rcon} -server -log -SteamAppId={steamAppID}",
				RconSyntax = "?RCONEnabled=True?RCONPort={rcon_port}?ServerAdminPassword=\"{rcon_pass}\"",
				Port = 7777,
				QueryPort = 27015,
				GameModes = ["PVE", "PVP"],
				RelativeConfigPath = @"ShooterGame\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["CubeWorld_Light"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Atlas",
				AppID = "1006030",
				ExeName = @"ShooterGame\Binaries\Win64\ShooterGameServer.exe",
				RequiredArgs = "Ocean?ServerX=0?ServerY=0?AltSaveDirectoryName=\"{map}\"?ServerPVE={mode}?ServerAdminPassword=\"{adminpass}\"?MaxPlayers={MaxPlayers}?Port={port}?QueryPort={query} {rcon} ?SeamlessIP=0.0.0.0 -log -server -SteamAppId={steamAppID}",
				RconSyntax = "?RCONEnabled=True?RCONPort={rcon_port}?ServerAdminPassword=\"{rcon_pass}\"",
				Port = 57555,
				QueryPort = 57555,
				GameModes = ["True", "False"],
				RelativeConfigPath = @"ShooterGame\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["00"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "SCUM",
				AppID = "3792580",
				ExeName = @"SCUM\Binaries\Win64\SCUMServer-Win64-Shipping.exe",
				RequiredArgs = "Port={port} QueryPort={query} -ServerName=\"{ServerName}\" -SteamAppId={steamAppID}",
				RelativeConfigPath = @"SCUM\Saved\Config\WindowsServer\ServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7042,
				QueryPort = 7043,
				Maps = ["SCUM_Island"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Eco",
				AppID = "739590",
				ExeName = "EcoServer.exe",
				RequiredArgs = "-nogui -port {port} -SteamAppId={steamAppID}",
				Port = 3000,
				QueryPort = 3001,
				RelativeConfigPath = @"Configs\Network.eco",
				Format = ConfigFormat.JSON,
				Maps = ["DefaultWorld"]
			},
			new()
			{
				Game = "SCP: Secret Laboratory",
				AppID = "996560",
				ExeName = "LocalAdmin.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 7777,
				Format = ConfigFormat.StandardINI,
				Maps = ["Facility"]
			},
			new()
			{
				Game = "Wurm Unlimited",
				AppID = "402370",
				ExeName = "WurmServerLauncher-64.exe",
				RequiredArgs = "{map} -SteamAppId={steamAppID}",
				Port = 3724,
				QueryPort = 27016,
				RelativeConfigPath = @"Creative\gameserver.conf",
				Format = ConfigFormat.StandardINI,
				Maps = ["Adventure"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Nightingale",
				AppID = "3796810",
				ExeName = "NWXServer.exe",
				RequiredArgs = "{map}?Listen -log -ServerName=\"{ServerName}\" -Password=\"{pass}\" -Port={port} -QueryPort={query} -SteamAppId={steamAppID}",
				RelativeConfigPath = @"NWX\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7777,
				QueryPort = 27015,
				Maps = ["SylvanGlade"],
				NeedsConfigWarning = true
			},
			new()
			{
				Game = "Holdfast: Nations At War",
				AppID = "1424230",
				ExeName = "Holdfast NaW - Dedicated Server.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -server_name=\"{ServerName}\" -port={port} -query_port={query} -map_name=\"{map}\"",
				Port = 20101,
				QueryPort = 27015,
				RelativeConfigPath = @"Holdfast NaW_Data\StreamingAssets\Config\serverConfig_Core.txt",
				Format = ConfigFormat.StandardINI,
				Maps = ["FortSchwarz", "CampNile"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Sven Co-op",
				AppID = "276060",
				ExeName = "svends.exe",
				RequiredArgs = "-console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"svencoop\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["stadium4"]
			},
			new() {
				Game = "The Isle",
				AppID = "412680",
				ExeName = @"TheIsle\Binaries\Win64\TheIsleServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Listen?ServerName=\"{ServerName}\"?ServerPassword=\"{pass}\"?Port={port}?QueryPort={query} -log -SteamAppId={steamAppID}",
				RelativeConfigPath = @"TheIsle\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Port = 7777,
				QueryPort = 27015,
				Maps = ["Spiro", "Gateway"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Rising Storm 2: Vietnam",
				AppID = "418480",
				ExeName = @"Binaries\Win64\VNGame.exe",
				RequiredArgs = "{map}?MaxPlayers={MaxPlayers} -Port={port} -QueryPort={query} -Log=ServerLog.log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"ROGame\Config\ROGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["VNTE-SongBe", "VNSU-AnLaoValley"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Hurtworld",
				AppID = "405100",
				ExeName = "Hurtworld.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -exec \"host {port};queryport {query};servername {ServerName};addadmin {adminpass}\" -logfile \"gamelog.txt\"",
				Port = 12871,
				QueryPort = 12881,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Day of Dragons",
				AppID = "1088320",
				ExeName = @"Dragons\Binaries\Win64\DragonsServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Dragons\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["OpenWorld"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Miscreated",
				AppID = "302200",
				ExeName = @"Bin64_dedicated\MiscreatedServer.exe",
				RequiredArgs = "-sv_port {port} +sv_maxplayers {MaxPlayers} +sv_servername \"{ServerName}\" +map {map} -SteamAppId={steamAppID}",
				Port = 64090,
				QueryPort = 64091,
				RelativeConfigPath = "miscreated.db",
				Format = ConfigFormat.StandardINI,
				Maps = ["islands"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "American Truck Simulator",
				AppID = "2239530", 
				ExeName = @"bin\win_x64\amtrucks_server.exe",
				RequiredArgs = "-dedicated -server_config server_config.sii -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_config.sii",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Life is Feudal: Your Own",
				AppID = "320850",
				ExeName = "DedicatedServer.exe",
				RequiredArgs = "-world {map} -port {port} -SteamAppId={steamAppID}",
				Port = 28000,
				QueryPort = 28001,
				RelativeConfigPath = "config_local.xml",
				Format = ConfigFormat.XML,
				Maps = ["yo_main"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Citadel: Forged with Fire",
				AppID = "489650",
				ExeName = @"Citadel\Binaries\Win64\CitadelServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Citadel\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Ignus"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "CryoFall",
				AppID = "1061710",
				ExeName = "CryoFall_Server.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 6000,
				QueryPort = 6000,
				RelativeConfigPath = "Settings.xml",
				Format = ConfigFormat.XML,
				Maps = ["Default"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Counter-Strike: Source",
				AppID = "232330",
				ExeName = "srcds.exe",
				RequiredArgs = "-game cstrike -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"cstrike\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["de_dust2", "cs_office"]
			},
			new() {
				Game = "Day of Defeat: Source",
				AppID = "232290",
				ExeName = "srcds.exe",
				RequiredArgs = "-game dod -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"dod\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["dod_donner", "dod_avalanche"]
			},
			new() {
				Game = "Half-Life 2: Deathmatch",
				AppID = "232370",
				ExeName = "srcds.exe",
				RequiredArgs = "-game hl2mp -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"hl2mp\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["crossfire", "bounce", "data-core", "ns_mines"]
			},
			new() {
				Game = "Left 4 Dead (1)",
				AppID = "222840",
				ExeName = "srcds.exe",
				RequiredArgs = "-game left4dead -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"left4dead\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["l4d_hospital01_apartment"]
			},
			new() {
				Game = "Day of Infamy",
				AppID = "462310", 
				ExeName = "srcds.exe",
				RequiredArgs = "-game doi -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"doi\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["bastogne", "dog_red"]
			},
			new() {
				Game = "Insurgency (2014)",
				AppID = "237410",
				ExeName = "srcds.exe",
				RequiredArgs = "-game insurgency -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"insurgency\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["market", "sinjar"]
			},
			new() {
				Game = "Killing Floor",
				AppID = "215350",
				ExeName = "ucc.exe",
				RequiredArgs = "server {map}.rom?game=KFmod.KFGameType?VACProtected=true -port={port} -SteamAppId={steamAppID}",
				Port = 7707,
				QueryPort = 7708,
				Format = ConfigFormat.StandardINI,
				Maps = ["KF-BioticsLab"]
			},
			new() {
				Game = "Black Mesa",
				AppID = "346680", 
				ExeName = "srcds.exe",
				RequiredArgs = "-game bms -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"bms\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["bm_c1a0a", "bm_c1a1a"]
			},
			new() {
				Game = "Contagion",
				AppID = "293030",
				ExeName = "srcds.exe",
				RequiredArgs = "-game contagion -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"contagion\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ce_barlowsquare", "ce_roanokepd"]
			},
			new() {
				Game = "Dino D-Day",
				AppID = "70010",
				ExeName = "srcds.exe",
				RequiredArgs = "-game dinodday -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"dinodday\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ddd_desiccant", "ddd_fortress"]
			},
			new() {
				Game = "Primal Carnage: Extinction",
				AppID = "336400",
				ExeName = @"Binaries\Win64\PrimalCarnageServer.exe",
				RequiredArgs = "{map}?MaxPlayers={MaxPlayers}?Port={port}?QueryPort={query} -server -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"PrimalCarnage\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["PC-Docks"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Memories of Mars",
				AppID = "897590",
				ExeName = @"MemoriesOfMars\Binaries\Win64\MemoriesOfMarsServer.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"MemoriesOfMars\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Mars"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Fistful of Frags",
				AppID = "295230", 
				ExeName = "srcds.exe",
				RequiredArgs = "-game fof -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"fof\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["fof_robertlee", "fof_desperados"]
			},
			new() {
				Game = "Wreckfest",
				AppID = "361580", 
				ExeName = "Wreckfest.exe",
				RequiredArgs = "-s server_config.cfg -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_config.cfg",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Assetto Corsa",
				AppID = "302550", 
				ExeName = "acServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 9600,
				QueryPort = 9601,
				RelativeConfigPath = @"cfg\server_cfg.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["imola", "monza", "spa"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Last Oasis",
				AppID = "920720",
				ExeName = @"OasisServer\Binaries\Win64\OasisServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Dark and Light",
				AppID = "630230",
				ExeName = @"DNL\Binaries\Win64\DNLServer.exe",
				RequiredArgs = "{map}?Listen?Port={port}?QueryPort={query} -server -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"DNL\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["TheArchos"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Zombie Panic! Source",
				AppID = "17505",
				ExeName = "srcds.exe",
				RequiredArgs = "-game zps -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"zps\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["zps_cinema", "zps_policestation"]
			},
			new() {
				Game = "Alien Swarm: Reactive Drop",
				AppID = "582400",
				ExeName = "srcds.exe",
				RequiredArgs = "-game reactivedrop -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"reactivedrop\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["asi-jac1-landingbay_01"]
			},
			new() {
				Game = "Half-Life Deathmatch: Source",
				AppID = "255470",
				ExeName = "srcds.exe",
				RequiredArgs = "-game hl1mp -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"hl1mp\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["crossfire", "stalkyard"]
			},
			new() {
				Game = "Soldat",
				AppID = "638500",
				ExeName = "soldatserver.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 23073,
				QueryPort = 23073,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Project CARS 2",
				AppID = "413770",
				ExeName = "pCARS2AVServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_config.json",
				Format = ConfigFormat.JSON
			},
			new() {
				Game = "ASKA",
				AppID = "3246670",
				ExeName = "ASKAServer.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -port {port} -queryport {query} -name \"{ServerName}\" -password \"{pass}\"",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_settings.json",
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Pavlov VR",
				AppID = "622970",
				ExeName = @"Pavlov\Binaries\Win64\PavlovServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Pavlov\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Half-Life Dedicated Server",
				AppID = "90", 
				ExeName = "hlds.exe",
				RequiredArgs = "-console -game valve +port {port} +maxplayers {MaxPlayers} +map {map} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"valve\config.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["crossfire", "bounce", "data-core"]
			},
			new() {
				Game = "Ground Branch",
				AppID = "476400",
				ExeName = @"GroundBranch\Binaries\Win64\GroundBranchServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -ServerName=\"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"GroundBranch\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Red Orchestra 2: Heroes of Stalingrad",
				AppID = "212542",
				ExeName = @"Binaries\Win64\ROGame.exe",
				RequiredArgs = "{map}?MaxPlayers={MaxPlayers} -Port={port} -QueryPort={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"ROGame\Config\ROGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["TE-Apartments", "TE-Gumrak"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Beasts of Bermuda",
				AppID = "882430",
				ExeName = @"BeastsOfBermuda\Binaries\Win64\BeastsOfBermudaServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"BeastsOfBermuda\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "The Isle (Evrima)",
				AppID = "412680",
				ExeName = @"TheIsle\Binaries\Win64\TheIsleServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Listen?Port={port}?QueryPort={query} -log -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"TheIsle\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Gateway"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Pirates, Vikings, and Knights II",
				AppID = "17575",
				ExeName = "srcds.exe",
				RequiredArgs = "-game pvkii -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"pvkii\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["tw_tortuga", "bt_island"]
			},
			new() {
				Game = "Foundry",
				AppID = "2915550",
				ExeName = "FoundryDedicatedServerLauncher.bat",
				RequiredArgs = "server_port={port} server_query_port={query} server_name=\"{ServerName}\" server_max_players={MaxPlayers} server_password=\"{pass}\" -SteamAppId={steamAppID}",
				Port = 3724,
				QueryPort = 27015,
				RelativeConfigPath = @"app.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Default"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Hellion",
				AppID = "598850",
				ExeName = "HellionServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "GameServer.ini",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Rising World",
				AppID = "339010",
				ExeName = "RisingWorldServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 4255,
				QueryPort = 4255,
				RelativeConfigPath = "server.properties",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Creativerse",
				AppID = "1098260",
				ExeName = "CreativerseServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				Format = ConfigFormat.JSON
			},
			new() {
				Game = "Heat",
				AppID = "996600",
				ExeName = "HeatServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "ServerSettings.ini",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Automobilista 2",
				AppID = "1338040", 
				ExeName = "AMS2DedicatedServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_config.json",
				Format = ConfigFormat.JSON
			},
			new() {
				Game = "Assetto Corsa Competizione",
				AppID = "1430110", 
				ExeName = "accServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 9000,
				QueryPort = 9001,
				RelativeConfigPath = @"cfg\settings.json",
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "rFactor 2",
				AppID = "400300", 
				ExeName = "rFactor2Dedicated.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 54297,
				QueryPort = 54297,
				RelativeConfigPath = @"UserData\player\Multiplayer.json",
				Format = ConfigFormat.JSON
			},
			new() {
				Game = "Painkiller: Hell & Damnation",
				AppID = "230030", 
				ExeName = "PainkillerServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Quake Live",
				AppID = "349090", 
				ExeName = "QuakeLiveServer.exe",
				RequiredArgs = "+set net_port {port} -SteamAppId={steamAppID}",
				Port = 27960,
				QueryPort = 27960,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Medieval Engineers",
				AppID = "367970",
				ExeName = @"DedicatedServer64\MedievalEngineersDedicated.exe",
				RequiredArgs = "-console -noconsole -path {map} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = @"Instance\MedievalEngineers-Dedicated.cfg",
				Format = ConfigFormat.XML,
				Maps = ["Default"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "BattleBit Remastered",
				AppID = "689410",
				ExeName = "BattleBitDedicated.exe",
				RequiredArgs = "-port {port} -queryport {query} -servername \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 30000,
				QueryPort = 30001,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Euro Truck Simulator 2",
				AppID = "1948160",
				ExeName = @"bin\win_x64\eurotrucks2.exe",
				RequiredArgs = "-dedicated -server_config server_config.sii -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server_config.sii",
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Natural Selection 2",
				AppID = "4940", 
				ExeName = "Server.exe",
				RequiredArgs = "-name \"{ServerName}\" -port {port} -limit {MaxPlayers} -map {map} -config_path \"config\" -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = @"config\ServerConfig.json",
				Format = ConfigFormat.JSON,
				Maps = ["ns2_docking", "ns2_summit"]
			},
			new() {
				Game = "Return to Moria",
				AppID = "3349480",
				ExeName = @"Moria\Binaries\Win64\MoriaServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Reign of Kings",
				AppID = "381690",
				ExeName = "ROK.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -port {port}",
				Port = 7350,
				QueryPort = 7350,
				RelativeConfigPath = @"Configuration\ServerSettings.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Stormhold"]
			},
			new() {
				Game = "Outlaws of the Old West",
				AppID = "915070",
				ExeName = @"Outlaws\Binaries\Win64\OutlawsServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Outlaws\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Outlaws"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Squad 44 (Post Scriptum)",
				AppID = "746200",
				ExeName = "PostScriptumServer.exe",
				RequiredArgs = "Port={port} QueryPort={query} FIXEDMAXPLAYERS={MaxPlayers} +map {map} -SteamAppId={steamAppID}",
				Port = 7787,
				QueryPort = 27165,
				RelativeConfigPath = @"PostScriptum\ServerConfig\Server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Carentan_AAS_v1"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "SCP: 5K",
				AppID = "884110",
				ExeName = @"Pandemic\Binaries\Win64\PandemicServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Darkest Hour: Europe '44-'45",
				AppID = "1290",
				ExeName = "RedOrchestra.exe",
				RequiredArgs = "server {map}?Listen -port={port} -SteamAppId={steamAppID}",
				Port = 7757,
				QueryPort = 7758,
				Format = ConfigFormat.StandardINI,
				Maps = ["DH-Stonne"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Fortress Forever",
				AppID = "329710",
				ExeName = "srcds.exe",
				RequiredArgs = "-game fortressforever -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"fortressforever\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ff_2fort", "ff_well"]
			},
			new() {
				Game = "Nuclear Dawn",
				AppID = "111710",
				ExeName = "srcds.exe",
				RequiredArgs = "-game nucleardawn -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"nucleardawn\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["nd_hydro", "nd_metro"]
			},
			new() {
				Game = "Military Conflict: Vietnam",
				AppID = "1136190",
				ExeName = "srcds.exe",
				RequiredArgs = "-game vietnam -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"vietnam\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["vdm_hue"]
			},
			new() {
				Game = "Monday Night Combat",
				AppID = "63220",
				ExeName = "MNC.exe",
				RequiredArgs = "server {map}?Listen -port={port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				Maps = ["MNC-Crossfire"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "NS2: Combat",
				AppID = "313900",
				ExeName = "Server.exe",
				RequiredArgs = "-port {port} -name \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Operation: Harsh Doorstop",
				AppID = "950900",
				ExeName = @"HarshDoorstop\Binaries\Win64\HarshDoorstopServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -ServerName=\"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"HarshDoorstop\Saved\Config\WindowsServer\Engine.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "America's Army: Proving Grounds",
				AppID = "203300",
				ExeName = @"AAGame\Binaries\Win64\AAGameServer.exe",
				RequiredArgs = "server {map}?Port={port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				Maps = ["AA_Downtown"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "NEOTOKYO",
				AppID = "313600",
				ExeName = "srcds.exe",
				RequiredArgs = "-game neotokyo -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"neotokyo\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["nt_engage_ctg"]
			},
			new() {
				Game = "Just Cause 2: Multiplayer",
				AppID = "261140",
				ExeName = "JcmpServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 7777,
				RelativeConfigPath = "config.lua",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Out of Reach",
				AppID = "406800",
				ExeName = "OutOfReachServer.exe",
				RequiredArgs = "-batchmode -nographics -SteamAppId={steamAppID} -port {port}",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "ServerConfig.json",
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Blackwake",
				AppID = "423410",
				ExeName = "BlackwakeServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 27015,
				QueryPort = 27016,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Beyond the Wire",
				AppID = "1064780",
				ExeName = @"BeyondTheWire\Binaries\Win64\BeyondTheWireServer-Win64-Shipping.exe",
				RequiredArgs = "Port={port} QueryPort={query} FIXEDMAXPLAYERS={MaxPlayers} +map {map} -SteamAppId={steamAppID}",
				Port = 7787,
				QueryPort = 27165,
				RelativeConfigPath = @"BeyondTheWire\ServerConfig\Server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["Ancre_AAS_v1"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Colony Survival",
				AppID = "748090",
				ExeName = "ColonySurvivalServer.exe",
				RequiredArgs = "+server.port {port} +server.name \"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 27016,
				QueryPort = 27016,
				RelativeConfigPath = "config.json",
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "BrainBread 2",
				AppID = "475370",
				ExeName = "srcds.exe",
				RequiredArgs = "-game brainbread2 -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"brainbread2\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["bb_creek"]
			},
			new() {
				Game = "Synergy",
				AppID = "17525",
				ExeName = "srcds.exe",
				RequiredArgs = "-game synergy -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"synergy\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["syn_d1_trainstation_01"]
			},
			new() {
				Game = "The Haunted: Hell's Reach",
				AppID = "43210",
				ExeName = @"UDKGame\Binaries\Win64\HauntedServer.exe",
				RequiredArgs = "-port {port} -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI
			},
			new() {
				Game = "Codename CURE",
				AppID = "383410",
				ExeName = "srcds.exe",
				RequiredArgs = "-game cure -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"cure\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["cure_bunker"]
			},
			new() {
				Game = "Age of Chivalry",
				AppID = "17515",
				ExeName = "srcds.exe",
				RequiredArgs = "-game ageofchivalry -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"ageofchivalry\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["aoc_siege"]
			},
			new() {
				Game = "Empires Mod",
				AppID = "460040",
				ExeName = "srcds.exe",
				RequiredArgs = "-game empires -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"empires\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["emp_canyon"]
			},
			new() {
				Game = "E.Y.E: Divine Cybermancy",
				AppID = "91720",
				ExeName = "srcds.exe",
				RequiredArgs = "-game eye -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"eye\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["cc_temple"]
			},
			new() {
				Game = "Myth of Empires",
				AppID = "1794810",
				ExeName = @"MOE\Binaries\Win64\MOEServer-Win64-Shipping.exe",
				RequiredArgs = "{map}?Listen -server -log -SteamAppId={steamAppID} -Port={port} -QueryPort={query} -ServerName=\"{ServerName}\" -ServerPassword=\"{pass}\"",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"MOE\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				GameModes = ["PVE", "PVP"],
				Maps = ["ZhongZhou", "DongZhou"],
				NeedsConfigWarning = true
			},
			//-----------------------------------------------------------------------




			new() {
				Game = "No More Room in Hell",
				AppID = "317670",
				ExeName = "srcds.exe",
				RequiredArgs = "-game nmrih -console -port {port} -SteamAppId={steamAppID} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"nmrih\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["nmo_broadway", "nmo_cabin"]
			},
			new() {
				Game = "Deadside",
				AppID = "1275530",
				ExeName = @"DeadsideServer\Binaries\Win64\DeadsideServer-Win64-Shipping.exe",
				RequiredArgs = "-log -port={port} -queryport={query} -ServerName=\"{ServerName}\" -SteamAppId={steamAppID}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Desolate\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Necesse",
				AppID = "1169370",
				ExeName = @"jre\bin\java.exe",
				RequiredArgs = "-jar Server.jar -nogui -localdir -world \"{map}\" -port {port} -slots {MaxPlayers} -password \"{pass}\"",
				Port = 14159,
				QueryPort = 14159,
				RelativeConfigPath = @"cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["world"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Longvinter",
				AppID = "1639880",
				ExeName = @"Longvinter\Binaries\Win64\LongvinterServer-Win64-Shipping.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 27016,
				RelativeConfigPath = @"Longvinter\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Frozen Flame",
				AppID = "1348640",
				ExeName = "FrozenFlameServer.exe",
				RequiredArgs = "-log -MetaGameServerName=\"{ServerName}\" -Port={port} -QueryPort={query} -ServerPassword=\"{pass}\"",
				Port = 7777,
				QueryPort = 7778,
				RelativeConfigPath = @"FrozenFlame\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "VEIN",
				AppID = "2131400",
				ExeName = "VeinServer.exe",
				RequiredArgs = "-log -port={port} -QueryPort={query} -MaxPlayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 7778,
				NeedsConfigWarning = true
			},
			new() {
				Game = "IOSoccer",
				AppID = "673990",
				ExeName = "srcds.exe",
				RequiredArgs = "-game iosoccer -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"iosoccer\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["8v8_vienna"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Action: Source",
				AppID = "985050",
				ExeName = "srcds.exe",
				RequiredArgs = "-game ahl2 -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"ahl2\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["act_airport"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Logic World",
				AppID = "1252670",
				ExeName = @"Server\Server.exe",
				RequiredArgs = "",
				Port = 43531,
				QueryPort = 43531,
				RelativeConfigPath = "config.jecs",
				NeedsConfigWarning = true
			},
			new() {
				Game = "Serious Sam 2017",
				AppID = "564390",
				ExeName = @"Bin\x64\Sam2017_DedicatedServer.exe",
				RequiredArgs = "+exec server.cfg +gameoptions gameoptions.cfg +port {port} +sessionname \"{ServerName}\" +rcompass \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "D.I.P.R.I.P.",
				AppID = "17535",
				ExeName = "srcds.exe",
				RequiredArgs = "-steam -diprip -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"diprip\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["dm_city", "dm_dam", "dm_refinery"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Desynced",
				AppID = "2943070",
				ExeName = @"Desynced\Binaries\Win64\DesyncedServer.exe",
				RequiredArgs = "\"{map}.desynced\" -log -Port={port} -QueryPort={query}",
				Port = 27015,
				QueryPort = 27016,
				Format = ConfigFormat.StandardINI,
				Maps = ["server"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "RaceRoom",
				AppID = "354060",
				ExeName = "RRRE_Dedicated.exe",
				RequiredArgs = "",
				Port = 60000,
				QueryPort = 60002,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Project CARS",
				AppID = "332670",
				ExeName = "DedicatedServerCmd.exe",
				RequiredArgs = "",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.JSON,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Plains of Pain",
				AppID = "2227360",
				ExeName = "PlainsOfPain.exe",
				RequiredArgs = "-nographics -batchmode -localhost -startServer -ignorecompilererrors -maxPlayers {MaxPlayers} -serverName \"{ServerName}\" -worldId 1 -seed {seed} -worldSize {world_size} -mapId {map}",
				Port = 7777,
				QueryPort = 7777,
				WorldSeed = "12345",
				WorldSize = 5,
				Format = ConfigFormat.StandardINI,
				Maps = ["0"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "DeadPoly",
				AppID = "2208380",
				ExeName = @"DeadPoly\Binaries\Win64\DeadPolyServer.exe",
				RequiredArgs = "-log -port={port} -queryport={query}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"DeadPoly\Saved\Config\WindowsServer\Engine.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Survive the Nights",
				AppID = "1502300",
				ExeName = "STN_Dedicated_Server.exe",
				RequiredArgs = "-steamclientlaunch -nographics",
				Port = 7950,
				QueryPort = 7950,
				RelativeConfigPath = @"Config\ServerConfig.txt",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Evolution Survival",
				AppID = "3810500",
				ExeName = @"EvolutionSurvivalServer\EvolutionSurvivalServer.exe",
				RequiredArgs = "-log -Port={port} -QueryPort={query} -ServerName=\"{ServerName}\" -MaxPlayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"EvolutionSurvivalServer\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Craftopia",
				AppID = "1670340",
				ExeName = "Craftopia.exe",
				RequiredArgs = "-batchmode -nographics",
				Port = 6587,
				QueryPort = 6587,
				RelativeConfigPath = "ServerSetting.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "HYPERCHARGE: Unboxed",
				AppID = "1045940",
				ExeName = @"Unboxed\Binaries\Win64\UnboxedServer-Win64-Shipping.exe",
				RequiredArgs = "-log -Port={port} -QueryPort={query} -ServerName=\"{ServerName}\" -MaxPlayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"Unboxed\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["ToyPalace"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Dysterra",
				AppID = "2214780",
				ExeName = @"Dysterra\Binaries\Win64\DysterraServer-Win64-Shipping.exe",
				RequiredArgs = "-log -customserver -QueryPort={query} -rconip=127.0.0.1 -rconport={rcon_port} -rconpasswd=\"{rcon_pass}\" -EACServer -worldsettings=\"{map}.json\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"Dysterra\WorldSettings\MyServer.json",
				Format = ConfigFormat.JSON,
				Maps = ["MyServer"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Mainland",
				AppID = "3392870",
				ExeName = "MainlandServer.exe",
				RequiredArgs = "-log WorldMapLevel -Port={port} -QueryPort={query} -SteamPort=8766",
				Port = 7777,
				QueryPort = 27015,
				Format = ConfigFormat.StandardINI,
				Maps = ["WorldMapLevel"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Ships At Sea",
				AppID = "3951240",
				ExeName = "sasserver.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 15000,
				RelativeConfigPath = @"SAS\Saved\Config\WindowsServer\DedicatedServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Warfork",
				AppID = "1136510",
				ExeName = "wf_server_x64.exe",
				RequiredArgs = "",
				Port = 44400,
				QueryPort = 44400,
				RelativeConfigPath = @"basewf\dedicated_autoexec.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["wfdm1"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Night of the Dead",
				AppID = "1420710",
				ExeName = "StartServer.bat",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "ServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "No One Survived",
				AppID = "2329680",
				ExeName = "WRSHServer.exe",
				RequiredArgs = "-server -log -Port={port} -QueryPort={query}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"WRSH\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "D.A.T.A",
				AppID = "965690",
				ExeName = @"WindowsServer\ABYSS421\Binaries\Win64\ABYSS421Server.exe",
				RequiredArgs = "?AdminPassword=\"{adminpass}\" -server -log -SteamServerName=\"{ServerName}\" -QueryPort={query} -Port={port}",
				Port = 7777,
				QueryPort = 27105,
				Format = ConfigFormat.StandardINI,
				NeedsConfigWarning = true
			},
			new() {
				Game = "Eternal Silence",
				AppID = "17555",
				ExeName = "srcds.exe",
				RequiredArgs = "-console -game esmod -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"esmod\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["es_ice", "es_aethra"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Dystopia",
				AppID = "17585",
				ExeName = @"bin\win32\srcds.exe",
				RequiredArgs = "-console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"dystopia\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["dys_vaccine"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Insurgency Mod",
				AppID = "17705",
				ExeName = "srcds.exe",
				RequiredArgs = "-steam -insurgency -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" {rcon}",
				RconSyntax = "+rcon_password \"{rcon_pass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"insurgency\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ins_buhriz", "ins_karam"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Days of War",
				AppID = "541790",
				ExeName = @"DaysOfWar\Binaries\Win64\DaysOfWarServer-Win64-Shipping.exe",
				RequiredArgs = "{map} -log Port={port} QueryPort={query}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"DaysOfWar\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["dow_carentan"],
				NeedsConfigWarning = true
			},
						new() {
				Game = "ASTRONEER",
				AppID = "728470",
				ExeName = "AstroServer.exe",
				RequiredArgs = "",
				Port = 8777,
				QueryPort = 8777,
				RelativeConfigPath = @"Astro\Saved\Config\WindowsServer\AstroServerSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["Dedicated"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Tower Unite",
				AppID = "439660",
				ExeName = "TowerServer.exe",
				RequiredArgs = "{map} -log -Port={port} -nosteamclient -QueryPort={query}",
				Port = 7777,
				QueryPort = 27016,
				RelativeConfigPath = @"Tower\Saved\Config\WindowsServer\TowerServer.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["/Game/Maps/C_Condo"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Onset",
				AppID = "1204170",
				ExeName = "OnsetServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 7776,
				RelativeConfigPath = "server_config.json",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Archean",
				AppID = "3557220",
				ExeName = @"Archean-game\Archean_server.exe",
				RequiredArgs = "",
				Port = 8881,
				QueryPort = 8881,
				RelativeConfigPath = @"Archean-game\server.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Re.Poly",
				AppID = "1189160",
				ExeName = "RePolyServer.exe",
				RequiredArgs = "{map}?listen?QueryPort={query}?Port={port} -server -log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"RePoly\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["AspiraWorld"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Isles of Yore",
				AppID = "1827320",
				ExeName = "IslesOfYoreServer.exe",
				RequiredArgs = "-queryport={query} -log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"IslesOfYore\Saved\Config\WindowsServer\Engine.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "s&box",
				AppID = "1892930",
				ExeName = "sbox-server.exe",
				RequiredArgs = "+game facepunch.sandbox {map} +hostname \"{ServerName}\" +port {port} +net_query_port {query}",
				Port = 27015,
				QueryPort = 27016,
				Maps = ["facepunch.flatgrass"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Just Cause 3 Multiplayer",
				AppID = "619960",
				ExeName = "Server.exe",
				RequiredArgs = "",
				Port = 4200,
				QueryPort = 4203,
				RelativeConfigPath = "config.json",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Chivalry: Medieval Warfare",
				AppID = "220070",
				ExeName = @"Binaries\Win32\UDK.exe",
				RequiredArgs = "{map}?steamsockets -dedicated=true -seekfreeloadingserver -Port={port} -QueryPort={query} -maxplayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"UDKGame\Config\PCServer-UDKGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [
					"AOCFFA-Arena3_P",
					"AOCTO-Battlegrounds_v3_P",
					"AOCCTF-Moor_p",
					"AOCLTS-Hillside_P"
				],
				NeedsConfigWarning = true
			},
			new() {
				Game = "nanos world",
				AppID = "1936830",
				ExeName = "NanosWorldServer.exe",
				RequiredArgs = "--name \"{ServerName}\" --map \"{map}\" --port {port} --query_port {query} --max_players {MaxPlayers} --password \"{pass}\" --dedicated_server 1",
				Port = 7777,
				QueryPort = 7778,
				RelativeConfigPath = "Config.toml",
				Format = ConfigFormat.StandardINI,
				Maps = [
					"nanos-world::BlankMap",
					"nanos-world::OceanMap",
					"nanos-world::EmptyMap",
					"nanos-world::TestingMap"
				],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Angels Fall First",
				AppID = "407480",
				ExeName = @"Binaries\Win64\AFFGameServer.exe",
				RequiredArgs = "{map} -log -SEEKFREELOADINGSERVER -Port={port} -QueryPort={query} -maxplayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"AFFGame\Config\PCServer-AFFGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [
					"AFF-Errah",
					"AFF-Fortress",
					"AFF-Meudeverre",
					"AFF-Ixion"
				],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Chivalry: Deadliest Warrior",
				AppID = "258680",
				ExeName = @"Binaries\Win32\CDWLogging.exe",
				RequiredArgs = "{map}?steamsockets -dedicated=true -seekfreeloadingserver -Port={port} -QueryPort={query} -maxplayers={MaxPlayers}",
				Port = 7777,
				QueryPort = 7778,
				RelativeConfigPath = @"CDWGame\Config\PCServer-CDWGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["TD-Acropolis"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Wickland",
				AppID = "332510",
				ExeName = @"Binaries\Win32\Wickland.exe",
				RequiredArgs = "server {map}?game=UDKWickland.UDKWicklandGameTown?dedicated=true -Port={port}",
				Port = 7778,
				QueryPort = 7778,
				RelativeConfigPath = @"UDKGame\Config\UDKGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["WLT-FrontEndTown"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Serious Sam HD: The Second Encounter",
				AppID = "41015",
				ExeName = @"Bin\SamHD_TSE_DedicatedServer.exe",
				RequiredArgs = "+exec server.cfg +port {port} +maxplayers {MaxPlayers} +sessionname \"{ServerName}\"",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Serious Sam HD: The First Encounter",
				AppID = "41005",
				ExeName = @"Bin\SamHD_DedicatedServer.exe",
				RequiredArgs = "+exec server.cfg +port {port} +maxplayers {MaxPlayers} +sessionname \"{ServerName}\"",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Eden Star",
				AppID = "419790",
				ExeName = @"EdenGame\Binaries\Win64\EdenGameServer.exe",
				RequiredArgs = "-log -ServerName=\"{ServerName}\" -ServerMaxPlayers={MaxPlayers} -Port={port} -QueryPort={query} {rcon}",
				RconSyntax = "-RCONPassword=\"{rcon_pass}\" -RCONPort={rcon_port}",
				Port = 7777,
				QueryPort = 27017,
				RelativeConfigPath = @"EdenGame\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Reflex Arena",
				AppID = "329740",
				ExeName = "reflexded.exe",
				RequiredArgs = "+sv_hostname \"{ServerName}\" +sv_maxclients {MaxPlayers} +sv_public 1 +sv_gameport {port} +sv_steamport {query} +map {map}",
				Port = 25787,
				QueryPort = 25797,
				RelativeConfigPath = "dedicatedserver.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["cpm22"],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Takedown: Red Sabre",
				AppID = "261020",
				ExeName = @"Binaries\Win32\TakedownGameServer-Win32-Shipping.exe",
				RequiredArgs = "{map}?game=TakedownGame.{mode}?listen=1?bIsLanMatch=0?NumPublicConnections={MaxPlayers} -seekfreeloadingserver -Port={port} -QueryPort={query}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"TakedownGame\Config\PCServer-TakedownGame.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [
					"TD00_Biolab",
					"TD01_Facility",
					"TD02_RadarBase",
					"TD03_CargoShip"
				],
				GameModes = [
					"TDTEAMDEATHMATCHGAME",
					"TDATTACKANDDEFENDGAME",
					"TDLASTMANSTANDING"
				],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Sniper Elite 4",
				AppID = "568880",
				ExeName = @"bin\SniperElite4_Dedicated.exe",
				RequiredArgs = "-authport 27000 -gameport {port} -lobbyport {query} -updateport 27015 -exec Default.cfg",
				Port = 27005,
				QueryPort = 27010,
				RelativeConfigPath = "Default.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Serious Sam Classics: Revolution",
				AppID = "299310",
				ExeName = @"Bin\DedicatedServer.exe",
				RequiredArgs = "{mode}",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"Scripts\Dedicated\DefaultCoop\init",
				Format = ConfigFormat.StandardINI,
				Maps = [@"Levels\LevelsMP\1_1_Palenque.wld"],
				GameModes = [
					"DefaultCoop",
					"DefaultFragmatchSE",
					"DefaultScorematchSE"
				],
				NeedsConfigWarning = true
			},
			new() {
				Game = "RuneScape: Dragonwilds",
				AppID = "4019830",
				ExeName = "RSDragonwildsServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 7777,
				RelativeConfigPath = @"RSDragonwilds\Saved\Config\WindowsServer\DedicatedServer.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Silica",
				AppID = "2738040",
				ExeName = "Silica.exe",
				RequiredArgs = "",
				Port = 26900,
				QueryPort = 26901,
				RelativeConfigPath = @"Documents\Silica\ServerSettings.xml",
				Format = ConfigFormat.XML,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Nuclear Option",
				AppID = "3930080",
				ExeName = "NuclearOptionServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 7778,
				RelativeConfigPath = "DedicatedServerConfig.json",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "StarRupture",
				AppID = "3809400",
				ExeName = "StarRuptureServerEOS.exe",
				RequiredArgs = "-Log -port={port}",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "DSSettings.txt",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Saleblazers",
				AppID = "3099600",
				ExeName = @"Default\Saleblazers.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"AppData\LocalLow\Airstrafe Interactive\Saleblazers\DedicatedServerConfig.json",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Windrose",
				AppID = "4129620",
				ExeName = "WindroseServer.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"R5\ServerDescription.json",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Cubic Odyssey",
				AppID = "3858450",
				ExeName = @"server\CubicOdysseyServer.exe",
				RequiredArgs = "-MaxNumPlayers={MaxPlayers} -Port={port} -Password=\"{pass}\" -Gamemode={mode}",
				Port = 27001,
				QueryPort = 27002,
				RelativeConfigPath = @"config\server_config.txt",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				GameModes = ["adventure"],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Wreckfest 2",
				AppID = "3519390",
				ExeName = "start_community_server.bat",
				RequiredArgs = "",
				Port = 30100,
				QueryPort = 27015,
				RelativeConfigPath = "server_config.scnf",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Blade Symphony",
				AppID = "228780",
				ExeName = @"bin\win32\srcds.exe",
				RequiredArgs = "-console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"berimbau\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["duel_winter"],
			},
			new() {
				Game = "Jabroni Brawl: Episode 3",
				AppID = "869800",
				ExeName = @"bin\win64\jbep3.exe",
				RequiredArgs = "-game jbep3 -steam -console -port {port} +maxplayers {MaxPlayers} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"jbep3\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Team Fortress 2 Classified",
				AppID = "3557020",
				ExeName = "srcds_win64.exe",
				RequiredArgs = "-steam -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"tf2classified\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ctf_2fort", "cp_dustbowl"],
			},
			new() {
				Game = "Team Fortress 2: Gold Rush",
				AppID = "4007540",
				ExeName = "srcds_win64.exe",
				RequiredArgs = "-game tf_goldrush -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"tf_goldrush\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["cp_goldrush", "ctf_2fort"],
			},
			new() {
				Game = "Treason",
				AppID = "1875500",
				ExeName = "srcds.exe",
				RequiredArgs = "-game treason -console -port {port} +maxplayers {MaxPlayers} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"treason\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Team Fortress 2008",
				AppID = "955080",
				ExeName = "srcds.exe",
				RequiredArgs = "-game tf2008 -steam -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"tf2008\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["ctf_2fort", "cp_dustbowl"],
			},
			new() {
				Game = "Modular Combat",
				AppID = "366360",
				ExeName = @"2007\srcds.exe",
				RequiredArgs = "-steam -game modularcombat -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"modularcombat\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["dm_lockdown"],
			},
			new() {
				Game = "JBMod",
				AppID = "2181210",
				ExeName = "srcds.exe",
				RequiredArgs = "-game jbmod -console -port {port} +maxplayers {MaxPlayers} +map {map} +hostname \"{ServerName}\" +sv_password \"{pass}\" +rcon_password \"{adminpass}\"",
				Port = 27015,
				QueryPort = 27015,
				RelativeConfigPath = @"jbmod\cfg\server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = ["dm_lockdown"],
			},
			new() {
				Game = "QANGA",
				AppID = "1652070",
				ExeName = "QangaServer.exe",
				RequiredArgs = "/Game/Maps/Universe/L_Persistent_Universe? -server -log -port={port} -map={map} -sessionName=\"{ServerName}\" -QueryPort={query}",
				Port = 10000,
				QueryPort = 27016,
				RelativeConfigPath = @"Qanga\Saved\Config\WindowsServer\GameUserSettings.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["L_Persistent_Universe"],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Serious Sam 3: BFE",
				AppID = "41080",
				ExeName = @"Bin\Sam3_DedicatedServer.exe",
				RequiredArgs = "+exec server.cfg",
				Port = 27015,
				QueryPort = 27016,
				RelativeConfigPath = "server.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Right to Rule",
				AppID = "1003980",
				ExeName = @"RightToRule\Binaries\Win64\RightToRuleServer-Win64-Shipping.exe",
				RequiredArgs = "/Game/Maps/Lobby/LobbyMap?listen -log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = @"RightToRule\Saved\Config\WindowsServer\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = ["LobbyMap"],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "The Riftbreaker",
				AppID = "4114030",
				ExeName = "DedicatedServer.bat",
				RequiredArgs = "",
				Port = 6321,
				QueryPort = 6321,
				RelativeConfigPath = @"conf\initial_config.cfg",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true,
			},
			new() {
				Game = "Airmen",
				AppID = "680870",
				ExeName = "Airmen Server.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Undoing",
				AppID = "805210",
				ExeName = "UndoingServerTool.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "PlayerVs",
				AppID = "1023620",
				ExeName = "PlayerVsServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Zero World",
				AppID = "2070070",
				ExeName = "MGSurvivalServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "ZeroWorld\\Saved\\Config\\WindowsServer\\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "DUCKSIDE",
				AppID = "2690320",
				ExeName = "DucksideServer.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Puck",
				AppID = "3481440",
				ExeName = "Puck.exe",
				RequiredArgs = "",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "HELL'S NEW WORLD",
				AppID = "1041860",
				ExeName = "WindowsServer\\HellsNewWorld\\Binaries\\Win64\\HellsNewWorldServer.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "WindowsServer\\HellsNewWorld\\Saved\\Config\\WindowsServer\\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Sapiens",
				AppID = "2886350",
				ExeName = "SapiensServer.exe",
				RequiredArgs = "",
				Port = 16161,
				QueryPort = 16162,
				RelativeConfigPath = "",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Hanako: Honor & Blade",
				AppID = "668390",
				ExeName = "HanakoServer.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "Hanako\\Saved\\Config\\WindowsServer\\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Starground",
				AppID = "3754950",
				ExeName = "starground_server.console.exe",
				RequiredArgs = "--log-file user://logs/server.log -d pause",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.JSON,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Deadlived",
				AppID = "4122590",
				ExeName = "DeadlivedServer.exe",
				RequiredArgs = "-log -server",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "Deadlived\\Saved\\Config\\WindowsServer\\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "Battle Splash 2.0",
				AppID = "761080",
				ExeName = "Battle Splash 2.0.exe",
				RequiredArgs = "-batchmode -nographics -logfile \"output.txt\"",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
			new() {
				Game = "GROUND BRANCH CTE",
				AppID = "1207110",
				ExeName = "GroundBranch\\Binaries\\Win64\\GroundBranchServer-Win64-Shipping.exe",
				RequiredArgs = "-log",
				Port = 7777,
				QueryPort = 27015,
				RelativeConfigPath = "GroundBranch\\Saved\\Config\\WindowsServer\\Game.ini",
				Format = ConfigFormat.StandardINI,
				Maps = [],
				NeedsConfigWarning = true
			},
		];

		public static IReadOnlyList<GameInfo> GetGameList()
		{
			return games;
		}

		public static GameInfo? GetGame(string gameName)
		{
			return games.FirstOrDefault(g => g.Game.Equals(gameName, StringComparison.OrdinalIgnoreCase));
		}

		public class PostInstallStep
		{
			public string ActionType { get; init; } = "";

			public string TargetPath { get; init; } = "";

			public string FileContent { get; init; } = "";
		}
	}
}