// ============================================================================
// PROJECT: Synix Game Server Control Panel
// AUTHOR: Jason Turner (ubidzz)
// COPYRIGHT: © 2026 All Rights Reserved.
//
// LEGAL NOTICE:
// This source code is proprietary and confidential.
// 1. Permission is granted for PERSONAL, NON-COMMERCIAL use only.
// 2. You may modify this code for your own use, but you may NOT redistribute,
//    rebrand, or sell this code or derivative works without written consent.
// 3. The "Synix" brand and logic remain the property of Jason Turner.
// ============================================================================
#nullable enable
namespace Synix_Control_Panel.SynixApp.UI.Settings
{
	partial class ProblemReportSettingsPage
	{
		private System.ComponentModel.IContainer? components = null;

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_lifetimeCancellation.Cancel();
				_lifetimeCancellation.Dispose();
				components?.Dispose();
			}

			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			pageScroll = new Panel();
			reportCard = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard();
			lblReportTitle = new Label();
			lblServerType = new Label();
			cmbServerType = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsComboBox();
			lblFailedAction = new Label();
			cmbFailedAction = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsComboBox();
			lblSummary = new Label();
			txtSummary = new TextBox();
			lblWhatHappened = new Label();
			txtWhatHappened = new TextBox();
			lblExpected = new Label();
			txtExpected = new TextBox();
			lblEnglishReportWarning = new Label();
			lblPrivacyNotice = new Label();
			systemCard = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard();
			lblSystemTitle = new Label();
			lblSynixVersion = new Label();
			lblWindowsVersion = new Label();
			lblVerification = new Label();
			sendCard = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard();
			lblSendTitle = new Label();
			lblConnectionStatus = new Label();
			actionFlow = new FlowLayoutPanel();
			btnConnectGitHub = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton();
			btnDisconnectGitHub = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton();
			btnSubmitGitHub = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton();
			btnCopyReport = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton();
			btnOpenDiscord = new Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton();
			lblReportStatus = new Label();
			pageScroll.SuspendLayout();
			reportCard.SuspendLayout();
			systemCard.SuspendLayout();
			sendCard.SuspendLayout();
			actionFlow.SuspendLayout();
			SuspendLayout();
			pageScroll.AutoScroll = true;
			pageScroll.BackColor = Color.FromArgb(8, 13, 24);
			pageScroll.Controls.Add(reportCard);
			pageScroll.Controls.Add(systemCard);
			pageScroll.Controls.Add(sendCard);
			pageScroll.Dock = DockStyle.Fill;
			pageScroll.Location = new Point(0, 0);
			pageScroll.Margin = new Padding(0);
			pageScroll.Name = "pageScroll";
			pageScroll.Padding = new Padding(0, 0, 8, 24);
			pageScroll.Size = new Size(816, 520);
			pageScroll.TabIndex = 0;
			reportCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
			reportCard.BackColor = Color.FromArgb(17, 27, 45);
			reportCard.BorderColor = Color.FromArgb(38, 52, 77);
			reportCard.Controls.Add(lblReportTitle);
			reportCard.Controls.Add(lblServerType);
			reportCard.Controls.Add(cmbServerType);
			reportCard.Controls.Add(lblFailedAction);
			reportCard.Controls.Add(cmbFailedAction);
			reportCard.Controls.Add(lblSummary);
			reportCard.Controls.Add(txtSummary);
			reportCard.Controls.Add(lblWhatHappened);
			reportCard.Controls.Add(txtWhatHappened);
			reportCard.Controls.Add(lblExpected);
			reportCard.Controls.Add(txtExpected);
			reportCard.Controls.Add(lblEnglishReportWarning);
			reportCard.Controls.Add(lblPrivacyNotice);
			reportCard.CornerRadius = 13;
			reportCard.FillColor = Color.FromArgb(17, 27, 45);
			reportCard.Location = new Point(0, 0);
			reportCard.Margin = new Padding(0, 0, 0, 16);
			reportCard.Name = "reportCard";
			reportCard.Size = new Size(790, 482);
			reportCard.TabIndex = 0;
		lblReportTitle.AutoSize = true;
		lblReportTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblReportTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblReportTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblReportTitle.Location = new Point(22, 18);
		lblReportTitle.Name = "lblReportTitle";
		lblReportTitle.Size = new Size(152, 21);
		lblReportTitle.TabIndex = 0;
		lblReportTitle.Text = LocalizationManager.Get("Text.8A36792207EBAFED1B5B");
		lblServerType.AutoSize = true;
		lblServerType.BackColor = Color.FromArgb(17, 27, 45);
		lblServerType.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblServerType.ForeColor = Color.FromArgb(158, 172, 194);
		lblServerType.Location = new Point(22, 60);
		lblServerType.Name = "lblServerType";
		lblServerType.Size = new Size(70, 15);
		lblServerType.TabIndex = 1;
		lblServerType.Text = LocalizationManager.Get("Text.FA8EB4AD4CE1F506D941");
		cmbServerType.BackColor = Color.FromArgb(12, 21, 36);
		cmbServerType.AccessibleName = LocalizationManager.Get("Text.FA8EB4AD4CE1F506D941");
		cmbServerType.DrawMode = DrawMode.OwnerDrawFixed;
		cmbServerType.DropDownStyle = ComboBoxStyle.DropDownList;
		cmbServerType.ForeColor = Color.FromArgb(245, 247, 251);
		cmbServerType.FormattingEnabled = true;
		cmbServerType.ItemHeight = 28;
		cmbServerType.Location = new Point(22, 80);
		cmbServerType.Name = "cmbServerType";
		cmbServerType.Size = new Size(360, 34);
		cmbServerType.TabIndex = 2;
		cmbServerType.SelectedIndexChanged += cmbServerType_SelectedIndexChanged;
		lblFailedAction.AutoSize = true;
		lblFailedAction.BackColor = Color.FromArgb(17, 27, 45);
		lblFailedAction.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblFailedAction.ForeColor = Color.FromArgb(158, 172, 194);
		lblFailedAction.Location = new Point(406, 60);
		lblFailedAction.Name = "lblFailedAction";
		lblFailedAction.Size = new Size(118, 15);
		lblFailedAction.TabIndex = 3;
		lblFailedAction.Text = LocalizationManager.Get("Text.F48D9672621A29033BFE");
		cmbFailedAction.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		cmbFailedAction.AccessibleName = LocalizationManager.Get("Text.DDE7244B8E964BD733E4");
		cmbFailedAction.BackColor = Color.FromArgb(12, 21, 36);
		cmbFailedAction.DrawMode = DrawMode.OwnerDrawFixed;
		cmbFailedAction.DropDownStyle = ComboBoxStyle.DropDownList;
		cmbFailedAction.ForeColor = Color.FromArgb(245, 247, 251);
		cmbFailedAction.FormattingEnabled = true;
		cmbFailedAction.ItemHeight = 28;
		cmbFailedAction.Location = new Point(406, 80);
		cmbFailedAction.Name = "cmbFailedAction";
		cmbFailedAction.Size = new Size(360, 34);
		cmbFailedAction.TabIndex = 4;
		lblSummary.AutoSize = true;
		lblSummary.BackColor = Color.FromArgb(17, 27, 45);
		lblSummary.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblSummary.ForeColor = Color.FromArgb(158, 172, 194);
		lblSummary.Location = new Point(22, 130);
		lblSummary.Name = "lblSummary";
		lblSummary.Size = new Size(90, 15);
		lblSummary.TabIndex = 5;
		lblSummary.Text = LocalizationManager.Get("Text.C57D4ECC83B7A2C7DFA4");
		txtSummary.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtSummary.AccessibleName = LocalizationManager.Get("Text.6612929FD78E8C716C9E");
		txtSummary.BackColor = Color.FromArgb(12, 21, 36);
		txtSummary.BorderStyle = BorderStyle.FixedSingle;
		txtSummary.Font = new Font("Segoe UI", 10F);
		txtSummary.ForeColor = Color.FromArgb(245, 247, 251);
		txtSummary.Location = new Point(22, 150);
		txtSummary.MaxLength = 180;
		txtSummary.Name = "txtSummary";
		txtSummary.PlaceholderText = LocalizationManager.Get("Text.E83F8984B15353372DF8");
		txtSummary.Size = new Size(744, 25);
		txtSummary.TabIndex = 6;
		lblWhatHappened.AutoSize = true;
		lblWhatHappened.BackColor = Color.FromArgb(17, 27, 45);
		lblWhatHappened.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblWhatHappened.ForeColor = Color.FromArgb(158, 172, 194);
		lblWhatHappened.Location = new Point(22, 194);
		lblWhatHappened.Name = "lblWhatHappened";
		lblWhatHappened.Size = new Size(90, 15);
		lblWhatHappened.TabIndex = 7;
		lblWhatHappened.Text = LocalizationManager.Get("Text.C4DC542B511FD74F4016");
		txtWhatHappened.AcceptsReturn = true;
		txtWhatHappened.AccessibleName = LocalizationManager.Get("Text.483BD49023AE2BFB08DA");
		txtWhatHappened.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtWhatHappened.BackColor = Color.FromArgb(12, 21, 36);
		txtWhatHappened.BorderStyle = BorderStyle.FixedSingle;
		txtWhatHappened.Font = new Font("Segoe UI", 9.5F);
		txtWhatHappened.ForeColor = Color.FromArgb(245, 247, 251);
		txtWhatHappened.Location = new Point(22, 214);
		txtWhatHappened.MaxLength = 12000;
		txtWhatHappened.Multiline = true;
		txtWhatHappened.Name = "txtWhatHappened";
		txtWhatHappened.PlaceholderText = LocalizationManager.Get("Text.7083BACCFEE1C7E3CC47");
		txtWhatHappened.ScrollBars = ScrollBars.Vertical;
		txtWhatHappened.Size = new Size(744, 88);
		txtWhatHappened.TabIndex = 8;
		lblExpected.AutoSize = true;
		lblExpected.BackColor = Color.FromArgb(17, 27, 45);
		lblExpected.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblExpected.ForeColor = Color.FromArgb(158, 172, 194);
		lblExpected.Location = new Point(22, 320);
		lblExpected.Name = "lblExpected";
		lblExpected.Size = new Size(135, 15);
		lblExpected.TabIndex = 9;
		lblExpected.Text = LocalizationManager.Get("Text.7F4A2A64A3B6B93FCDCE");
		txtExpected.AcceptsReturn = true;
		txtExpected.AccessibleName = LocalizationManager.Get("Text.2F376BD10744D7EAB43E");
		txtExpected.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtExpected.BackColor = Color.FromArgb(12, 21, 36);
		txtExpected.BorderStyle = BorderStyle.FixedSingle;
		txtExpected.Font = new Font("Segoe UI", 9.5F);
		txtExpected.ForeColor = Color.FromArgb(245, 247, 251);
		txtExpected.Location = new Point(22, 340);
		txtExpected.MaxLength = 12000;
		txtExpected.Multiline = true;
		txtExpected.Name = "txtExpected";
		txtExpected.PlaceholderText = LocalizationManager.Get("Text.59BE71333C960FD08E7E");
		txtExpected.ScrollBars = ScrollBars.Vertical;
		txtExpected.Size = new Size(744, 72);
		txtExpected.TabIndex = 10;
		lblEnglishReportWarning.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblEnglishReportWarning.BackColor = Color.FromArgb(17, 27, 45);
		lblEnglishReportWarning.Font = new Font("Segoe UI", 8.75F, FontStyle.Bold);
		lblEnglishReportWarning.ForeColor = Color.FromArgb(45, 212, 191);
		lblEnglishReportWarning.Location = new Point(22, 418);
		lblEnglishReportWarning.Name = "lblEnglishReportWarning";
		lblEnglishReportWarning.Size = new Size(744, 36);
		lblEnglishReportWarning.TabIndex = 11;
		lblEnglishReportWarning.Text = LocalizationManager.Get("Report.EnglishRequiredWarning");
		lblEnglishReportWarning.Visible = false;
		lblPrivacyNotice.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblPrivacyNotice.BackColor = Color.FromArgb(17, 27, 45);
		lblPrivacyNotice.Font = new Font("Segoe UI", 8.75F);
		lblPrivacyNotice.ForeColor = Color.FromArgb(245, 185, 76);
		lblPrivacyNotice.Location = new Point(22, 426);
		lblPrivacyNotice.Name = "lblPrivacyNotice";
		lblPrivacyNotice.Size = new Size(744, 38);
		lblPrivacyNotice.TabIndex = 12;
		lblPrivacyNotice.Text = LocalizationManager.Get("Text.0BB9D8B879FB1885FD71");
		systemCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		systemCard.BackColor = Color.FromArgb(17, 27, 45);
		systemCard.BorderColor = Color.FromArgb(38, 52, 77);
		systemCard.Controls.Add(lblSystemTitle);
		systemCard.Controls.Add(lblSynixVersion);
		systemCard.Controls.Add(lblWindowsVersion);
		systemCard.Controls.Add(lblVerification);
		systemCard.CornerRadius = 13;
		systemCard.FillColor = Color.FromArgb(17, 27, 45);
		systemCard.Location = new Point(0, 498);
		systemCard.Margin = new Padding(0, 0, 0, 16);
		systemCard.Name = "systemCard";
		systemCard.Size = new Size(790, 214);
		systemCard.TabIndex = 1;
		lblSystemTitle.AutoSize = true;
		lblSystemTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblSystemTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblSystemTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblSystemTitle.Location = new Point(22, 18);
		lblSystemTitle.Name = "lblSystemTitle";
		lblSystemTitle.Size = new Size(188, 21);
		lblSystemTitle.TabIndex = 0;
		lblSystemTitle.Text = LocalizationManager.Get("Text.7AF2440D6D8533178C93");
		lblSynixVersion.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblSynixVersion.BackColor = Color.FromArgb(17, 27, 45);
		lblSynixVersion.Font = new Font("Segoe UI", 9.25F);
		lblSynixVersion.ForeColor = Color.FromArgb(158, 172, 194);
		lblSynixVersion.Location = new Point(22, 58);
		lblSynixVersion.Name = "lblSynixVersion";
		lblSynixVersion.Size = new Size(744, 22);
		lblSynixVersion.TabIndex = 1;
		lblSynixVersion.Text = LocalizationManager.Get("Text.06EA49BA268B1386ABC4");
		lblWindowsVersion.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblWindowsVersion.BackColor = Color.FromArgb(17, 27, 45);
		lblWindowsVersion.Font = new Font("Segoe UI", 9.25F);
		lblWindowsVersion.ForeColor = Color.FromArgb(158, 172, 194);
		lblWindowsVersion.Location = new Point(22, 84);
		lblWindowsVersion.Name = "lblWindowsVersion";
		lblWindowsVersion.Size = new Size(744, 22);
		lblWindowsVersion.TabIndex = 2;
		lblWindowsVersion.Text = LocalizationManager.Get("Text.84447CC03EF09445AAA2");
		lblVerification.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblVerification.BackColor = Color.FromArgb(17, 27, 45);
		lblVerification.Font = new Font("Segoe UI", 9F);
		lblVerification.ForeColor = Color.FromArgb(158, 172, 194);
		lblVerification.Location = new Point(22, 116);
		lblVerification.Name = "lblVerification";
		lblVerification.Size = new Size(744, 78);
		lblVerification.TabIndex = 3;
		lblVerification.Text = LocalizationManager.Get("Text.58ECD5D931201294DE1E");
		sendCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		sendCard.BackColor = Color.FromArgb(17, 27, 45);
		sendCard.BorderColor = Color.FromArgb(38, 52, 77);
		sendCard.Controls.Add(lblSendTitle);
		sendCard.Controls.Add(lblConnectionStatus);
			sendCard.Controls.Add(actionFlow);
		sendCard.Controls.Add(lblReportStatus);
		sendCard.CornerRadius = 13;
		sendCard.FillColor = Color.FromArgb(17, 27, 45);
		sendCard.Location = new Point(0, 728);
		sendCard.Margin = new Padding(0, 0, 0, 24);
		sendCard.Name = "sendCard";
			sendCard.Size = new Size(790, 278);
		sendCard.TabIndex = 2;
		lblSendTitle.AutoSize = true;
		lblSendTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblSendTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblSendTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblSendTitle.Location = new Point(22, 18);
		lblSendTitle.Name = "lblSendTitle";
		lblSendTitle.Size = new Size(139, 21);
		lblSendTitle.TabIndex = 0;
		lblSendTitle.Text = LocalizationManager.Get("Text.FCF1E140E39DFF4DBC74");
		lblConnectionStatus.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblConnectionStatus.BackColor = Color.FromArgb(17, 27, 45);
		lblConnectionStatus.Font = new Font("Segoe UI", 9.25F);
		lblConnectionStatus.ForeColor = Color.FromArgb(158, 172, 194);
		lblConnectionStatus.Location = new Point(22, 51);
		lblConnectionStatus.Name = "lblConnectionStatus";
		lblConnectionStatus.Size = new Size(744, 25);
		lblConnectionStatus.TabIndex = 1;
		lblConnectionStatus.Text = LocalizationManager.Get("Text.88ED3B522C4F0A8BD740");
		actionFlow.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		actionFlow.BackColor = Color.FromArgb(17, 27, 45);
		actionFlow.Controls.Add(btnConnectGitHub);
		actionFlow.Controls.Add(btnDisconnectGitHub);
		actionFlow.Controls.Add(btnSubmitGitHub);
		actionFlow.Controls.Add(btnCopyReport);
		actionFlow.Controls.Add(btnOpenDiscord);
		actionFlow.Location = new Point(22, 88);
		actionFlow.Margin = new Padding(0);
		actionFlow.Name = "actionFlow";
		actionFlow.Size = new Size(744, 94);
		actionFlow.TabIndex = 2;
		actionFlow.WrapContents = true;
		btnConnectGitHub.Location = new Point(0, 0);
		btnConnectGitHub.AccessibleName = LocalizationManager.Get("Text.2D4C39C3520C4D081530");
		btnConnectGitHub.Margin = new Padding(0, 0, 10, 10);
		btnConnectGitHub.Name = "btnConnectGitHub";
		btnConnectGitHub.Size = new Size(148, 42);
		btnConnectGitHub.TabIndex = 0;
		btnConnectGitHub.Text = LocalizationManager.Get("Text.4027E5B24418520F3EFE");
		btnConnectGitHub.UseAccentStyle = true;
		btnConnectGitHub.Click += btnConnectGitHub_Click;
		btnDisconnectGitHub.Location = new Point(158, 0);
		btnDisconnectGitHub.AccessibleName = LocalizationManager.Get("Text.F43D922729C65E06FA55");
		btnDisconnectGitHub.Margin = new Padding(0, 0, 10, 10);
		btnDisconnectGitHub.Name = "btnDisconnectGitHub";
		btnDisconnectGitHub.Size = new Size(148, 42);
		btnDisconnectGitHub.TabIndex = 1;
		btnDisconnectGitHub.Text = LocalizationManager.Get("Text.6C47B175B49C03E40EB6");
		btnDisconnectGitHub.Visible = false;
		btnDisconnectGitHub.Click += btnDisconnectGitHub_Click;
		btnSubmitGitHub.Location = new Point(316, 0);
		btnSubmitGitHub.AccessibleName = LocalizationManager.Get("Text.C40FC918931D3BA589D1");
		btnSubmitGitHub.Margin = new Padding(0, 0, 10, 10);
		btnSubmitGitHub.Name = "btnSubmitGitHub";
		btnSubmitGitHub.Size = new Size(158, 42);
		btnSubmitGitHub.TabIndex = 2;
		btnSubmitGitHub.Text = LocalizationManager.Get("Text.E447D358EDA1CE76C466");
		btnSubmitGitHub.UseAccentStyle = true;
		btnSubmitGitHub.Click += btnSubmitGitHub_Click;
		btnCopyReport.Location = new Point(484, 0);
		btnCopyReport.AccessibleName = LocalizationManager.Get("Text.62372ADDC6612D415FFA");
		btnCopyReport.Margin = new Padding(0, 0, 10, 10);
		btnCopyReport.Name = "btnCopyReport";
		btnCopyReport.Size = new Size(132, 42);
		btnCopyReport.TabIndex = 3;
		btnCopyReport.Text = LocalizationManager.Get("Text.54B8E0C0C268C1549AF4");
		btnCopyReport.Click += btnCopyReport_Click;
		btnOpenDiscord.Location = new Point(626, 0);
		btnOpenDiscord.AccessibleName = LocalizationManager.Get("Text.0D36C28AC26B4782FB6E");
		btnOpenDiscord.Margin = new Padding(0, 0, 10, 10);
		btnOpenDiscord.Name = "btnOpenDiscord";
		btnOpenDiscord.Size = new Size(152, 42);
		btnOpenDiscord.TabIndex = 4;
		btnOpenDiscord.Text = LocalizationManager.Get("Text.44760C7627E84170448C");
		btnOpenDiscord.Click += btnOpenDiscord_Click;
		lblReportStatus.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblReportStatus.BackColor = Color.FromArgb(17, 27, 45);
		lblReportStatus.Font = new Font("Segoe UI", 9F);
		lblReportStatus.ForeColor = Color.FromArgb(105, 124, 153);
		lblReportStatus.Location = new Point(22, 194);
		lblReportStatus.Name = "lblReportStatus";
		lblReportStatus.Size = new Size(744, 64);
		lblReportStatus.TabIndex = 7;
		lblReportStatus.Text = LocalizationManager.Get("Text.9942D957346A0E83C15C");
		AutoScaleDimensions = new SizeF(96F, 96F);
		AutoScaleMode = AutoScaleMode.Dpi;
		BackColor = Color.FromArgb(8, 13, 24);
		Controls.Add(pageScroll);
		Name = "ProblemReportSettingsPage";
		Size = new Size(816, 520);
		pageScroll.ResumeLayout(false);
		reportCard.ResumeLayout(false);
		reportCard.PerformLayout();
		systemCard.ResumeLayout(false);
		systemCard.PerformLayout();
		sendCard.ResumeLayout(false);
		sendCard.PerformLayout();
		actionFlow.ResumeLayout(false);
		ResumeLayout(false);
		}

		private Panel pageScroll = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard reportCard = null!;
		private Label lblReportTitle = null!;
		private Label lblServerType = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsComboBox cmbServerType = null!;
		private Label lblFailedAction = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsComboBox cmbFailedAction = null!;
		private Label lblSummary = null!;
		private TextBox txtSummary = null!;
		private Label lblWhatHappened = null!;
		private TextBox txtWhatHappened = null!;
		private Label lblExpected = null!;
		private TextBox txtExpected = null!;
		private Label lblEnglishReportWarning = null!;
		private Label lblPrivacyNotice = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard systemCard = null!;
		private Label lblSystemTitle = null!;
		private Label lblSynixVersion = null!;
		private Label lblWindowsVersion = null!;
		private Label lblVerification = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsCard sendCard = null!;
		private Label lblSendTitle = null!;
		private Label lblConnectionStatus = null!;
		private FlowLayoutPanel actionFlow = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton btnConnectGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton btnDisconnectGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton btnSubmitGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton btnCopyReport = null!;
		private Synix_Control_Panel.SynixApp.Design.Controls.ModernSettingsButton btnOpenDiscord = null!;
		private Label lblReportStatus = null!;
	}
}
