// ============================================================================
// PROJECT: Synix Game Server Control Panel
// AUTHOR: Jason Turner (ubidzz)
// COPYRIGHT: © 2026 All Rights Reserved.
//
// LEGAL NOTICE:
// This source code is proprietary and confidential.
// 1. Permission is granted for PERSONAL, NON-COMMERCIAL use only.
// 2. You may modify this code for your own use, but you may NOT redistribute,
//    rebrand, or sell this code or derivative works without written consent.
// 3. The "Synix" brand and logic remain the property of Jason Turner.
// ============================================================================
#nullable enable
namespace Synix_Control_Panel.SynixEngine
{
	partial class ProblemReportSettingsPage
	{
		private System.ComponentModel.IContainer? components = null;

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				_lifetimeCancellation.Cancel();
				_lifetimeCancellation.Dispose();
				components?.Dispose();
			}

			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			pageScroll = new Panel();
			reportCard = new Synix_Control_Panel.SynixApp.Design.ModernSettingsCard();
			lblReportTitle = new Label();
			lblServerType = new Label();
			cmbServerType = new Synix_Control_Panel.SynixApp.Design.ModernSettingsComboBox();
			lblFailedAction = new Label();
			cmbFailedAction = new Synix_Control_Panel.SynixApp.Design.ModernSettingsComboBox();
			lblSummary = new Label();
			txtSummary = new TextBox();
			lblWhatHappened = new Label();
			txtWhatHappened = new TextBox();
			lblExpected = new Label();
			txtExpected = new TextBox();
			lblEnglishReportWarning = new Label();
			lblPrivacyNotice = new Label();
			systemCard = new Synix_Control_Panel.SynixApp.Design.ModernSettingsCard();
			lblSystemTitle = new Label();
			lblSynixVersion = new Label();
			lblWindowsVersion = new Label();
			lblVerification = new Label();
			sendCard = new Synix_Control_Panel.SynixApp.Design.ModernSettingsCard();
			lblSendTitle = new Label();
			lblConnectionStatus = new Label();
			actionFlow = new FlowLayoutPanel();
			btnConnectGitHub = new Synix_Control_Panel.SynixApp.Design.ModernSettingsButton();
			btnDisconnectGitHub = new Synix_Control_Panel.SynixApp.Design.ModernSettingsButton();
			btnSubmitGitHub = new Synix_Control_Panel.SynixApp.Design.ModernSettingsButton();
			btnCopyReport = new Synix_Control_Panel.SynixApp.Design.ModernSettingsButton();
			btnOpenDiscord = new Synix_Control_Panel.SynixApp.Design.ModernSettingsButton();
			lblReportStatus = new Label();
			pageScroll.SuspendLayout();
			reportCard.SuspendLayout();
			systemCard.SuspendLayout();
			sendCard.SuspendLayout();
			actionFlow.SuspendLayout();
			SuspendLayout();
			pageScroll.AutoScroll = true;
			pageScroll.BackColor = Color.FromArgb(8, 13, 24);
			pageScroll.Controls.Add(reportCard);
			pageScroll.Controls.Add(systemCard);
			pageScroll.Controls.Add(sendCard);
			pageScroll.Dock = DockStyle.Fill;
			pageScroll.Location = new Point(0, 0);
			pageScroll.Margin = new Padding(0);
			pageScroll.Name = "pageScroll";
			pageScroll.Padding = new Padding(0, 0, 8, 24);
			pageScroll.Size = new Size(816, 520);
			pageScroll.TabIndex = 0;
			reportCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
			reportCard.BackColor = Color.FromArgb(17, 27, 45);
			reportCard.BorderColor = Color.FromArgb(38, 52, 77);
			reportCard.Controls.Add(lblReportTitle);
			reportCard.Controls.Add(lblServerType);
			reportCard.Controls.Add(cmbServerType);
			reportCard.Controls.Add(lblFailedAction);
			reportCard.Controls.Add(cmbFailedAction);
			reportCard.Controls.Add(lblSummary);
			reportCard.Controls.Add(txtSummary);
			reportCard.Controls.Add(lblWhatHappened);
			reportCard.Controls.Add(txtWhatHappened);
			reportCard.Controls.Add(lblExpected);
			reportCard.Controls.Add(txtExpected);
			reportCard.Controls.Add(lblEnglishReportWarning);
			reportCard.Controls.Add(lblPrivacyNotice);
			reportCard.CornerRadius = 13;
			reportCard.FillColor = Color.FromArgb(17, 27, 45);
			reportCard.Location = new Point(0, 0);
			reportCard.Margin = new Padding(0, 0, 0, 16);
			reportCard.Name = "reportCard";
			reportCard.Size = new Size(790, 482);
			reportCard.TabIndex = 0;
		lblReportTitle.AutoSize = true;
		lblReportTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblReportTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblReportTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblReportTitle.Location = new Point(22, 18);
		lblReportTitle.Name = "lblReportTitle";
		lblReportTitle.Size = new Size(152, 21);
		lblReportTitle.TabIndex = 0;
		lblReportTitle.Text = "Describe the problem";
		lblServerType.AutoSize = true;
		lblServerType.BackColor = Color.FromArgb(17, 27, 45);
		lblServerType.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblServerType.ForeColor = Color.FromArgb(158, 172, 194);
		lblServerType.Location = new Point(22, 60);
		lblServerType.Name = "lblServerType";
		lblServerType.Size = new Size(70, 15);
		lblServerType.TabIndex = 1;
		lblServerType.Text = "Server type";
		cmbServerType.BackColor = Color.FromArgb(12, 21, 36);
		cmbServerType.AccessibleName = "Server type";
		cmbServerType.DrawMode = DrawMode.OwnerDrawFixed;
		cmbServerType.DropDownStyle = ComboBoxStyle.DropDownList;
		cmbServerType.ForeColor = Color.FromArgb(245, 247, 251);
		cmbServerType.FormattingEnabled = true;
		cmbServerType.ItemHeight = 28;
		cmbServerType.Location = new Point(22, 80);
		cmbServerType.Name = "cmbServerType";
		cmbServerType.Size = new Size(360, 34);
		cmbServerType.TabIndex = 2;
		cmbServerType.SelectedIndexChanged += cmbServerType_SelectedIndexChanged;
		lblFailedAction.AutoSize = true;
		lblFailedAction.BackColor = Color.FromArgb(17, 27, 45);
		lblFailedAction.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblFailedAction.ForeColor = Color.FromArgb(158, 172, 194);
		lblFailedAction.Location = new Point(406, 60);
		lblFailedAction.Name = "lblFailedAction";
		lblFailedAction.Size = new Size(118, 15);
		lblFailedAction.TabIndex = 3;
		lblFailedAction.Text = "What were you doing?";
		cmbFailedAction.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		cmbFailedAction.AccessibleName = "What Synix was doing when the problem happened";
		cmbFailedAction.BackColor = Color.FromArgb(12, 21, 36);
		cmbFailedAction.DrawMode = DrawMode.OwnerDrawFixed;
		cmbFailedAction.DropDownStyle = ComboBoxStyle.DropDownList;
		cmbFailedAction.ForeColor = Color.FromArgb(245, 247, 251);
		cmbFailedAction.FormattingEnabled = true;
		cmbFailedAction.ItemHeight = 28;
		cmbFailedAction.Location = new Point(406, 80);
		cmbFailedAction.Name = "cmbFailedAction";
		cmbFailedAction.Size = new Size(360, 34);
		cmbFailedAction.TabIndex = 4;
		lblSummary.AutoSize = true;
		lblSummary.BackColor = Color.FromArgb(17, 27, 45);
		lblSummary.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblSummary.ForeColor = Color.FromArgb(158, 172, 194);
		lblSummary.Location = new Point(22, 130);
		lblSummary.Name = "lblSummary";
		lblSummary.Size = new Size(90, 15);
		lblSummary.TabIndex = 5;
		lblSummary.Text = "Short summary";
		txtSummary.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtSummary.AccessibleName = "Problem summary";
		txtSummary.BackColor = Color.FromArgb(12, 21, 36);
		txtSummary.BorderStyle = BorderStyle.FixedSingle;
		txtSummary.Font = new Font("Segoe UI", 10F);
		txtSummary.ForeColor = Color.FromArgb(245, 247, 251);
		txtSummary.Location = new Point(22, 150);
		txtSummary.MaxLength = 180;
		txtSummary.Name = "txtSummary";
		txtSummary.PlaceholderText = "Example: Server closes a few seconds after Start";
		txtSummary.Size = new Size(744, 25);
		txtSummary.TabIndex = 6;
		lblWhatHappened.AutoSize = true;
		lblWhatHappened.BackColor = Color.FromArgb(17, 27, 45);
		lblWhatHappened.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblWhatHappened.ForeColor = Color.FromArgb(158, 172, 194);
		lblWhatHappened.Location = new Point(22, 194);
		lblWhatHappened.Name = "lblWhatHappened";
		lblWhatHappened.Size = new Size(90, 15);
		lblWhatHappened.TabIndex = 7;
		lblWhatHappened.Text = "What happened?";
		txtWhatHappened.AcceptsReturn = true;
		txtWhatHappened.AccessibleName = "What happened";
		txtWhatHappened.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtWhatHappened.BackColor = Color.FromArgb(12, 21, 36);
		txtWhatHappened.BorderStyle = BorderStyle.FixedSingle;
		txtWhatHappened.Font = new Font("Segoe UI", 9.5F);
		txtWhatHappened.ForeColor = Color.FromArgb(245, 247, 251);
		txtWhatHappened.Location = new Point(22, 214);
		txtWhatHappened.MaxLength = 12000;
		txtWhatHappened.Multiline = true;
		txtWhatHappened.Name = "txtWhatHappened";
		txtWhatHappened.PlaceholderText = "Tell us what you clicked, what Synix displayed, and how to make it happen again.";
		txtWhatHappened.ScrollBars = ScrollBars.Vertical;
		txtWhatHappened.Size = new Size(744, 88);
		txtWhatHappened.TabIndex = 8;
		lblExpected.AutoSize = true;
		lblExpected.BackColor = Color.FromArgb(17, 27, 45);
		lblExpected.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
		lblExpected.ForeColor = Color.FromArgb(158, 172, 194);
		lblExpected.Location = new Point(22, 320);
		lblExpected.Name = "lblExpected";
		lblExpected.Size = new Size(135, 15);
		lblExpected.TabIndex = 9;
		lblExpected.Text = "What should have happened?";
		txtExpected.AcceptsReturn = true;
		txtExpected.AccessibleName = "Expected result";
		txtExpected.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		txtExpected.BackColor = Color.FromArgb(12, 21, 36);
		txtExpected.BorderStyle = BorderStyle.FixedSingle;
		txtExpected.Font = new Font("Segoe UI", 9.5F);
		txtExpected.ForeColor = Color.FromArgb(245, 247, 251);
		txtExpected.Location = new Point(22, 340);
		txtExpected.MaxLength = 12000;
		txtExpected.Multiline = true;
		txtExpected.Name = "txtExpected";
		txtExpected.PlaceholderText = "Optional";
		txtExpected.ScrollBars = ScrollBars.Vertical;
		txtExpected.Size = new Size(744, 72);
		txtExpected.TabIndex = 10;
		lblEnglishReportWarning.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblEnglishReportWarning.BackColor = Color.FromArgb(17, 27, 45);
		lblEnglishReportWarning.Font = new Font("Segoe UI", 8.75F, FontStyle.Bold);
		lblEnglishReportWarning.ForeColor = Color.FromArgb(45, 212, 191);
		lblEnglishReportWarning.Location = new Point(22, 418);
		lblEnglishReportWarning.Name = "lblEnglishReportWarning";
		lblEnglishReportWarning.Size = new Size(744, 36);
		lblEnglishReportWarning.TabIndex = 11;
		lblEnglishReportWarning.Text = "Important: Write the summary and report details in English so the Synix support team can review them.";
		lblEnglishReportWarning.Visible = false;
		lblPrivacyNotice.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblPrivacyNotice.BackColor = Color.FromArgb(17, 27, 45);
		lblPrivacyNotice.Font = new Font("Segoe UI", 8.75F);
		lblPrivacyNotice.ForeColor = Color.FromArgb(245, 185, 76);
		lblPrivacyNotice.Location = new Point(22, 426);
		lblPrivacyNotice.Name = "lblPrivacyNotice";
		lblPrivacyNotice.Size = new Size(744, 38);
		lblPrivacyNotice.TabIndex = 12;
		lblPrivacyNotice.Text = "Do not paste passwords, webhooks, IP addresses, private configuration, or full launch commands. Synix removes common secrets before sending.";
		systemCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		systemCard.BackColor = Color.FromArgb(17, 27, 45);
		systemCard.BorderColor = Color.FromArgb(38, 52, 77);
		systemCard.Controls.Add(lblSystemTitle);
		systemCard.Controls.Add(lblSynixVersion);
		systemCard.Controls.Add(lblWindowsVersion);
		systemCard.Controls.Add(lblVerification);
		systemCard.CornerRadius = 13;
		systemCard.FillColor = Color.FromArgb(17, 27, 45);
		systemCard.Location = new Point(0, 498);
		systemCard.Margin = new Padding(0, 0, 0, 16);
		systemCard.Name = "systemCard";
		systemCard.Size = new Size(790, 214);
		systemCard.TabIndex = 1;
		lblSystemTitle.AutoSize = true;
		lblSystemTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblSystemTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblSystemTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblSystemTitle.Location = new Point(22, 18);
		lblSystemTitle.Name = "lblSystemTitle";
		lblSystemTitle.Size = new Size(188, 21);
		lblSystemTitle.TabIndex = 0;
		lblSystemTitle.Text = "Added automatically";
		lblSynixVersion.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblSynixVersion.BackColor = Color.FromArgb(17, 27, 45);
		lblSynixVersion.Font = new Font("Segoe UI", 9.25F);
		lblSynixVersion.ForeColor = Color.FromArgb(158, 172, 194);
		lblSynixVersion.Location = new Point(22, 58);
		lblSynixVersion.Name = "lblSynixVersion";
		lblSynixVersion.Size = new Size(744, 22);
		lblSynixVersion.TabIndex = 1;
		lblSynixVersion.Text = "Synix version:";
		lblWindowsVersion.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblWindowsVersion.BackColor = Color.FromArgb(17, 27, 45);
		lblWindowsVersion.Font = new Font("Segoe UI", 9.25F);
		lblWindowsVersion.ForeColor = Color.FromArgb(158, 172, 194);
		lblWindowsVersion.Location = new Point(22, 84);
		lblWindowsVersion.Name = "lblWindowsVersion";
		lblWindowsVersion.Size = new Size(744, 22);
		lblWindowsVersion.TabIndex = 2;
		lblWindowsVersion.Text = "Windows version:";
		lblVerification.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblVerification.BackColor = Color.FromArgb(17, 27, 45);
		lblVerification.Font = new Font("Segoe UI", 9F);
		lblVerification.ForeColor = Color.FromArgb(158, 172, 194);
		lblVerification.Location = new Point(22, 116);
		lblVerification.Name = "lblVerification";
		lblVerification.Size = new Size(744, 78);
		lblVerification.TabIndex = 3;
		lblVerification.Text = "Choose a server type to show its local verification history.";
		sendCard.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		sendCard.BackColor = Color.FromArgb(17, 27, 45);
		sendCard.BorderColor = Color.FromArgb(38, 52, 77);
		sendCard.Controls.Add(lblSendTitle);
		sendCard.Controls.Add(lblConnectionStatus);
			sendCard.Controls.Add(actionFlow);
		sendCard.Controls.Add(lblReportStatus);
		sendCard.CornerRadius = 13;
		sendCard.FillColor = Color.FromArgb(17, 27, 45);
		sendCard.Location = new Point(0, 728);
		sendCard.Margin = new Padding(0, 0, 0, 24);
		sendCard.Name = "sendCard";
			sendCard.Size = new Size(790, 278);
		sendCard.TabIndex = 2;
		lblSendTitle.AutoSize = true;
		lblSendTitle.BackColor = Color.FromArgb(17, 27, 45);
		lblSendTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
		lblSendTitle.ForeColor = Color.FromArgb(245, 247, 251);
		lblSendTitle.Location = new Point(22, 18);
		lblSendTitle.Name = "lblSendTitle";
		lblSendTitle.Size = new Size(139, 21);
		lblSendTitle.TabIndex = 0;
		lblSendTitle.Text = "Send your report";
		lblConnectionStatus.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblConnectionStatus.BackColor = Color.FromArgb(17, 27, 45);
		lblConnectionStatus.Font = new Font("Segoe UI", 9.25F);
		lblConnectionStatus.ForeColor = Color.FromArgb(158, 172, 194);
		lblConnectionStatus.Location = new Point(22, 51);
		lblConnectionStatus.Name = "lblConnectionStatus";
		lblConnectionStatus.Size = new Size(744, 25);
		lblConnectionStatus.TabIndex = 1;
		lblConnectionStatus.Text = "GitHub is not connected. Copy and Discord options still work.";
		actionFlow.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		actionFlow.BackColor = Color.FromArgb(17, 27, 45);
		actionFlow.Controls.Add(btnConnectGitHub);
		actionFlow.Controls.Add(btnDisconnectGitHub);
		actionFlow.Controls.Add(btnSubmitGitHub);
		actionFlow.Controls.Add(btnCopyReport);
		actionFlow.Controls.Add(btnOpenDiscord);
		actionFlow.Location = new Point(22, 88);
		actionFlow.Margin = new Padding(0);
		actionFlow.Name = "actionFlow";
		actionFlow.Size = new Size(744, 94);
		actionFlow.TabIndex = 2;
		actionFlow.WrapContents = true;
		btnConnectGitHub.Location = new Point(0, 0);
		btnConnectGitHub.AccessibleName = "Connect GitHub account";
		btnConnectGitHub.Margin = new Padding(0, 0, 10, 10);
		btnConnectGitHub.Name = "btnConnectGitHub";
		btnConnectGitHub.Size = new Size(148, 42);
		btnConnectGitHub.TabIndex = 0;
		btnConnectGitHub.Text = "Connect GitHub";
		btnConnectGitHub.UseAccentStyle = true;
		btnConnectGitHub.Click += btnConnectGitHub_Click;
		btnDisconnectGitHub.Location = new Point(158, 0);
		btnDisconnectGitHub.AccessibleName = "Disconnect GitHub account";
		btnDisconnectGitHub.Margin = new Padding(0, 0, 10, 10);
		btnDisconnectGitHub.Name = "btnDisconnectGitHub";
		btnDisconnectGitHub.Size = new Size(148, 42);
		btnDisconnectGitHub.TabIndex = 1;
		btnDisconnectGitHub.Text = "Disconnect GitHub";
		btnDisconnectGitHub.Visible = false;
		btnDisconnectGitHub.Click += btnDisconnectGitHub_Click;
		btnSubmitGitHub.Location = new Point(316, 0);
		btnSubmitGitHub.AccessibleName = "Submit problem report to GitHub";
		btnSubmitGitHub.Margin = new Padding(0, 0, 10, 10);
		btnSubmitGitHub.Name = "btnSubmitGitHub";
		btnSubmitGitHub.Size = new Size(158, 42);
		btnSubmitGitHub.TabIndex = 2;
		btnSubmitGitHub.Text = "Submit to GitHub";
		btnSubmitGitHub.UseAccentStyle = true;
		btnSubmitGitHub.Click += btnSubmitGitHub_Click;
		btnCopyReport.Location = new Point(484, 0);
		btnCopyReport.AccessibleName = "Copy problem report";
		btnCopyReport.Margin = new Padding(0, 0, 10, 10);
		btnCopyReport.Name = "btnCopyReport";
		btnCopyReport.Size = new Size(132, 42);
		btnCopyReport.TabIndex = 3;
		btnCopyReport.Text = "Copy Report";
		btnCopyReport.Click += btnCopyReport_Click;
		btnOpenDiscord.Location = new Point(626, 0);
		btnOpenDiscord.AccessibleName = "Open Discord bug forum";
		btnOpenDiscord.Margin = new Padding(0, 0, 10, 10);
		btnOpenDiscord.Name = "btnOpenDiscord";
		btnOpenDiscord.Size = new Size(152, 42);
		btnOpenDiscord.TabIndex = 4;
		btnOpenDiscord.Text = "Open Discord";
		btnOpenDiscord.Click += btnOpenDiscord_Click;
		lblReportStatus.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
		lblReportStatus.BackColor = Color.FromArgb(17, 27, 45);
		lblReportStatus.Font = new Font("Segoe UI", 9F);
		lblReportStatus.ForeColor = Color.FromArgb(105, 124, 153);
		lblReportStatus.Location = new Point(22, 194);
		lblReportStatus.Name = "lblReportStatus";
		lblReportStatus.Size = new Size(744, 64);
		lblReportStatus.TabIndex = 7;
		lblReportStatus.Text = "GitHub posts directly without opening a browser after the account is connected.";
		AutoScaleDimensions = new SizeF(96F, 96F);
		AutoScaleMode = AutoScaleMode.Dpi;
		BackColor = Color.FromArgb(8, 13, 24);
		Controls.Add(pageScroll);
		Name = "ProblemReportSettingsPage";
		Size = new Size(816, 520);
		pageScroll.ResumeLayout(false);
		reportCard.ResumeLayout(false);
		reportCard.PerformLayout();
		systemCard.ResumeLayout(false);
		systemCard.PerformLayout();
		sendCard.ResumeLayout(false);
		sendCard.PerformLayout();
		actionFlow.ResumeLayout(false);
		ResumeLayout(false);
		}

		private Panel pageScroll = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsCard reportCard = null!;
		private Label lblReportTitle = null!;
		private Label lblServerType = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsComboBox cmbServerType = null!;
		private Label lblFailedAction = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsComboBox cmbFailedAction = null!;
		private Label lblSummary = null!;
		private TextBox txtSummary = null!;
		private Label lblWhatHappened = null!;
		private TextBox txtWhatHappened = null!;
		private Label lblExpected = null!;
		private TextBox txtExpected = null!;
		private Label lblEnglishReportWarning = null!;
		private Label lblPrivacyNotice = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsCard systemCard = null!;
		private Label lblSystemTitle = null!;
		private Label lblSynixVersion = null!;
		private Label lblWindowsVersion = null!;
		private Label lblVerification = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsCard sendCard = null!;
		private Label lblSendTitle = null!;
		private Label lblConnectionStatus = null!;
		private FlowLayoutPanel actionFlow = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsButton btnConnectGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsButton btnDisconnectGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsButton btnSubmitGitHub = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsButton btnCopyReport = null!;
		private Synix_Control_Panel.SynixApp.Design.ModernSettingsButton btnOpenDiscord = null!;
		private Label lblReportStatus = null!;
	}
}
